### ISSUE TITLE
Fuel Wallet support for nightly/beta-5 tagged releases

### ISSUE THREAD

**Issue by haardikk21** [FuelLabs/fuels-wallet#1003]
### Motivation

Hey folks,

With the nightly channel of `forc` and other components, there seems to be some breaking changes in the way a local Fuel Core node is set up (re: `consensus_parameters` vs `transaction_parameters` and such)

The Fuel Wallet currently I beleive caps out at support for beta-4. For the course we're building @LearnWeb3DAO we rely on the nightly/beta-5 tagged components for certain features and bug fixes and would love to have the Fuel Wallet be at a point where it's usable and we can build the project's related UI functionality beyond just the contracts

**Comment by luizstacio** [comment]
Hi @haardikk21 sorry for the delay. You can find a version of the Wallet compatible with beta-5 here: https://next-wallet.fuel.network, this version will be on the Chrome WebStore in the next days, for now you can follow the steps ["Install from source code"](https://next-wallet.fuel.network/docs/install/#install-from-source-code)
