### ISSUE TITLE
Add SwaySwap assets error

### ISSUE THREAD

**Issue by goddam55** [FuelLabs/fuels-wallet#1018]
### What version of Wallet are you using?

0.13.10

### What is happening?

https://fuellabs.github.io/swayswap/welcome/add-assets

This page can not run Add SwaySwap assets. 

It show "Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid"
![2023-12-30_094316](https://github.com/FuelLabs/fuels-wallet/assets/154046833/20532b08-412e-4570-96da-5ad9462879be)

### steps to reproduce

-

### How it should behave?

-

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

120.0.6099.130

**Comment by Bikram0545** [comment]
same problem still exist

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.
