### ISSUE TITLE
Wallet not detected showing always the install button

### ISSUE THREAD

**Issue by bharmalhtm** [FuelLabs/fuels-wallet#1019]
### What version of Wallet are you using?

0.13.10

### What is happening?

When i am trying to connecting in Alpha bridge with Meta mask then its is connecting to sepolia network but whenever i am trying to connect chrome extension it is showing error that **to connect your Fuel wallet, Install the browser extension ** while it is already installed in my chrome.

### steps to reproduce

need to connect Fuel wallet extension in to chrome while bridging from sepolia network to fuel Network
<img width="950" alt="Screenshot 2024-01-01 163433" src="https://github.com/FuelLabs/fuels-wallet/assets/155360992/81414f0d-927e-46f4-8180-d56d5d9b80da">

### How it should behave?

need to connect Fuel wallet extension in to chrome while bridging from sepolia network to fuel Network and sing massage should be produced

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

120.0.6099.130

**Comment by luizstacio** [comment]
@bharmalhtm thanks for reporting the issue. Some questions;
1. Have you finish the setup of the Wallet? Created a seed phrase etc?
2. This happened only on the first try or if you refresh it works?
