### ISSUE TITLE
swap

### ISSUE THREAD

**Issue by wdsr44** [FuelLabs/fuels-wallet#1020]
### What version of Wallet are you using?

 beta 4

### What is happening?

Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid

### steps to reproduce

 no site https://fuellabs.github.io/swayswap/welcome/add-assets ta dando erro

### How it should behave?

![Captura de Tela (52)](https://github.com/FuelLabs/fuels-wallet/assets/153565517/570d0630-21af-4588-b60a-67c52d072969)
/ # @

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Versão 120.0.6099.130 (Versão oficial) 64 bits

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.
