### ISSUE TITLE
sway swap

### ISSUE THREAD

**Issue by arewaexchange** [FuelLabs/fuels-wallet#1021]
### What version of Wallet are you using?

chrome extention

### What is happening?

am trying to add token on swayswap, am getting error message.

### steps to reproduce

the third step on sway swap "add token"

### How it should behave?

it should add the token seamlessly

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

latest

**Comment by arewaexchange** [comment]
![Uploading Screenshot 2024-01-02 081336.png…]()

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.
