### ISSUE TITLE
showing decimal is not valid 

### ISSUE THREAD

**Issue by haris200106** [FuelLabs/fuels-wallet#1022]
### What version of Wallet are you using?

testnet beta 4

### What is happening?

Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid

### steps to reproduce

......

### How it should behave?

it should add assets withot error

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

latest

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.
