### ISSUE TITLE
Can't mint on fueart.io

### ISSUE THREAD

**Issue by Xpxwx** [FuelLabs/fuels-wallet#1025]
### What version of Wallet are you using?

0.13.10

### What is happening?

When trying to mint a nft on fuelart.io, I have the confirmation pop up that appears on my extension. The confirmation button shows "loading", then the pop up disappears. I tried several time and the problem's still going. 

### steps to reproduce

go there https://fuelart.io/launchpad/0x5d4f41b5e6249cca9d0a7c0af4a84ad802de75076a42e8af538eef76f0900729
connect wallet 
click on mint 

### How it should behave?

it should open a pop up for confirmation and allow me to confirm the transaction for mint

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 120.0.6099.130 (Build officiel) (64 bits)

**Comment by luizstacio** [comment]
@Xpxwx thanks for reporting a issue. I have inspect the application and the issue been returned is related to gasLimit, what is informed by the fuelart application. Please contact fuelart directly using the contact infos they have on the application. https://fuelart.io/
