### ISSUE TITLE
Failure to add asset

### ISSUE THREAD

**Issue by Zuka8008** [FuelLabs/fuels-wallet#1028]
### What version of Wallet are you using?

4

### What is happening?

Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid

### steps to reproduce

Trying to add asset on swayswap, tried to follow instructions from bot on discord server
quoted. To add an asset to your wallet, you can use the addAsset function with the asset's details like this: const asset = { assetId: BaseAssetId }; const isAdded = await fuel.addAsset(asset); [[1]](https://docs.fuel.network/docs/wallet/dev/reference/#add-asset). If you're using a user interface, you can click the "Add Asset" button and provide the asset ID, name, symbol, and image URL to add a new custom asset [[2]](https://docs.fuel.network/docs/wallet/how-to-use/#adding-custom-assets).

### How it should behave?

Asset adding to portfolio

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 120.0.6099.200 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.
