### ISSUE TITLE
Failed to execute 'insertBerfore'

### ISSUE THREAD

**Issue by Vania2803** [FuelLabs/fuels-wallet#1029]
Ola, bom dia. Nâo consigo fazer as interaçoes na carteira. poderiam me auxiliar oir favor...
![Captura de tela 2024-01-08 180135](https://github.com/FuelLabs/fuels-wallet/assets/126296349/7ffdea25-a53b-4aff-a2aa-228a8b3f1c63)

**Comment by luizstacio** [comment]
@Vania2803 can you explain the steps you took prior to visualize this error?

**Comment by Vania2803** [comment]
When asked to connect the wallet... it opens but closes. Then the wallet itself says that there is an error. I've tried several times... the same thing always happens.

**Comment by luizstacio** [comment]
@Vania2803 can you provide me some more information me to debug this error? What is the Operation System and version you are using? What is the version of the browser you are using?

**Comment by luizstacio** [comment]
@Vania2803 I was able to replicate the issue using a google translator, do you have it enabled to auto translate the pages?
