### ISSUE TITLE
SEND Token

### ISSUE THREAD

**Issue by jpcoco** [FuelLabs/fuels-wallet#1038]
### Motivation

when you want to send a token to another wallet account - when you press sEND, it would be nice to have a listing of all the wallets so that you can choose them more easily by name

**Comment by jpcoco** [comment]
![Capture](https://github.com/FuelLabs/fuels-wallet/assets/72105514/dcdacf79-6fba-4310-bd4e-51501542df29)
like that

**Comment by luizstacio** [comment]
Thanks for the feature request, we plan to have Contact Book in the feature, I'm going to link this issue there and close this, in order to keep our organization. https://github.com/FuelLabs/fuels-wallet/issues/651
