### ISSUE TITLE
Can't connect fuel wallet to Fuel Native Bridge

### ISSUE THREAD

**Issue by DR4G0N5** [FuelLabs/fuels-wallet#1040]
### What version of Wallet are you using?

Version: 0.13.10

### What is happening?

When try to bridge assets from mm on sepolia to fuel wallet on Fuel Native Bridge,no connection at all with the fuel wallet

### steps to reproduce

Tried all the necessarily steps to no avail

### How it should behave?

Ask for app connection

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

 120.0.6099.216

**Comment by luizstacio** [comment]
Hi we notice some users have a old version of the Fuel Wallet also installed on the browser can you check if your case is similar to this one: https://github.com/FuelLabs/fuels-wallet/issues/1019
