### ISSUE TITLE
add asserts get error

### ISSUE THREAD

**Issue by tanggen** [FuelLabs/fuels-wallet#1049]
### What version of Wallet are you using?

Version: 0.13.10

### What is happening?

when i Add SwaySwap assets from "https://fuellabs.github.io/swayswap/welcome/add-assets",i got error tips: Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid,and the console shows like this
![微信截图_20240116155619](https://github.com/FuelLabs/fuels-wallet/assets/4439611/523c1981-1712-455e-b8b0-41ce8bb7932f)

### steps to reproduce

just visit : https://fuellabs.github.io/swayswap/welcome/add-assets,click add assets

### How it should behave?

execute success

### What os are you seeing the problem on?

None

### What browser?

None

### What is your browser version?

google chrome 120.0.6099.217(64 bit)

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues as it do not support the newer versions of the SDK that require a asset to provide the amount o decimals. We have updated the project readme to better inform other users.
