### ISSUE TITLE
Error during adding assets on swayswap

### ISSUE THREAD

**Issue by tunamutlu5** [FuelLabs/fuels-wallet#1055]
### What version of Wallet are you using?

Testnet Beta 5

### What is happening?

Please see error on photo.

![Screenshot 2024-01-17 at 21 15 01](https://github.com/FuelLabs/fuels-wallet/assets/156478988/d616d749-e402-4b26-b1dd-f72b369c33d3)

### steps to reproduce

1) downloaded wallet, 2)required test tokens, 3) receiving error during receiving assets

### How it should behave?

all steps should be completed without any major issue.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Version 120.0.6099.234 (Official Build) (arm64)

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues as it do not support the newer versions of the SDK that require a asset to provide the amount o decimals. We have updated the project readme to better inform other users.
