### ISSUE TITLE
Unexpected end of JSON imput

### ISSUE THREAD

**Issue by DogenSrb** [FuelLabs/fuels-wallet#1061]
### What version of Wallet are you using?

0.13.10

### What is happening?

I wanted to transfer TKN from Sepolia to Feul network and stuck with step 3. Confirm transaction. When I click on Confirm transaction and Approve I get errro "Unexpected end of JSON imput"

![image](https://github.com/FuelLabs/fuels-wallet/assets/156659398/dbbfb41b-8acf-4259-bfe1-96dc3de0708d)

### steps to reproduce

d

### How it should behave?

d

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 120.0.6099.225 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
Hi @DogenSrb thanks for opening a issue. This was also found by our team and should be fixed once https://github.com/FuelLabs/fuels-portal/pull/198 is merged.

**Comment by DogenSrb** [comment]
Thank you!
