### ISSUE TITLE
Fuel Nomen not recognizing my FUEL wallet. It says "pls sign the transaction in your wallet" but nothing ever pops up/wallet never opens up for the signature. And yes, I did deactivate all other wallet extensions on google chrome, and this was the only active wallet at the time.

### ISSUE THREAD

**Issue by ZeManZotCom** [FuelLabs/fuels-wallet#1072]
### What version of Wallet are you using?

0.13.10

### What is happening?

Fuel Nomen not recognizing my FUEL wallet. It says "pls sign the transaction in your wallet" but nothing ever pops up/wallet never opens up for the signature. And yes, I did deactivate all other wallet extensions on google chrome, and this was the only active wallet at the time.

### steps to reproduce

connect wallet to FUEL nomen. DAPP never recognizes and as a result, it doesn't open up a page for the wallet.

### How it should behave?

Wallet should open when prompted.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
Hi @ZeManZotCom thanks for the issue. This looks to be a  problem related to the fuel nomen application and not the Fuel Wallet. You can create a issue directly on their project repository.
