### ISSUE TITLE
Is this a BUG

### ISSUE THREAD

**Issue by mohdmutala** [FuelLabs/fuels-wallet#1089]
### What version of Wallet are you using?

Version 0.13.10

### What is happening?

Every time i want to sign a transaction it ask me a password and it’s annoying 
![image](https://github.com/FuelLabs/fuels-wallet/assets/118211159/57ec1946-51f9-4823-841e-a808baa4df67)

### steps to reproduce

Ok it will be great if I unlock the fuel wallet once for like 1 hour before it locks 

### How it should behave?

I

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

V 1.62.165

**Comment by cold-briu** [comment]
Hi there! 
This is not a bug but an expected behavior.
We'll be taking this as a feature request, however, there's no guarantee that it is going to be implemented.
