### ISSUE TITLE
Cannot connect my browser Wallet Extension to Testnet BETA 5

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuels-wallet#1094]
### What version of Wallet are you using?

0.13.10

### What is happening?

I cannot add Testnet BETA 5 to the network, it might be that I have the incorrect URL, but I copied it from the CLI output and added /graphql to the end of the URL which is what the example seemed to be showing in the URL edit box. See image attached.

![testnet beta 5 error](https://github.com/FuelLabs/fuels-wallet/assets/114662397/1440dfe0-db2c-4eb2-b181-2dc1f6e96357)

### steps to reproduce

Click add network and then enter the URL

### How it should behave?

Once a new Testnet is available, it should be possible to add this network URL to the wallet so it switches to the latest Testnet.  Obviously within reason as wallet changes might be required to support the new network.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Version 121.0.6167.184 (Official Build) (x86_64)

**Comment by luizstacio** [comment]
@HoTandy the Fuel Wallet version 0.13.10 is only compatible with beta-4 network the version 0.15.2 should be compatible with beta-5 is going to be released soon. For now if you want to test beta-5 you can download the development wallet at https://next-wallet.fuel.network/docs/install/

**Comment by HoTandy** [comment]
Thanks @luizstacio, in that case we should close the "bug".
