### ISSUE TITLE
Website can't see Fuel wallet extension

### ISSUE THREAD

**Issue by nastyafrosty** [FuelLabs/fuels-wallet#1115]
### What version of Wallet are you using?

0.15.2

### What is happening?

I want to connect my Fuel wallet to the https://thundernft.market, but website doesn't "see" it and show "install" option. But Fuel wallet Chrome extension has been installed

### steps to reproduce

1. Go to the https://thundernft.market/marketplace  page
2. Click on the wallet icon on the right
![Screenshot_3](https://github.com/FuelLabs/fuels-wallet/assets/41231823/ab353b24-a260-4646-bf95-d7bb936be059)
![Screenshot_4](https://github.com/FuelLabs/fuels-wallet/assets/41231823/b2daa719-6b47-4099-bce5-e310bbdb1e7c)
3. Click on the Install button
4. Go to the Chrome extension page and see that wallet is already used
5. 
![Screenshot_5](https://github.com/FuelLabs/fuels-wallet/assets/41231823/f97f3e26-3a2b-4f8c-9543-5ff8109c666e)

### How it should behave?

I guess website should see that I have Fuel wallet and button should be "Connect wallet" instead of "Install"

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by LuizAsFight** [comment]
I just tested here and it worked, could you check again with updated wallet version? I see this issue was created a while ago and we had a lot of work done around connection with dapp @nastyafrosty

**Comment by LuizAsFight** [comment]
related to #1125 , closing for same reason, its fixed
