### ISSUE TITLE
Wallet Manager not Resetting Properly on Logout

### ISSUE THREAD

**Issue by keeplook** [FuelLabs/fuels-wallet#1122]
### What version of Wallet are you using?

latest

### What is happening?

Exit the mnemonic and import it again. The address with path 0 is correct, and the cache of subsequent paths has not been cleared. Starting from the last latest path, the second generated address is not 1

### steps to reproduce

Exit the mnemonic and import it again. The address with path 0 is correct, and the cache of subsequent paths has not been cleared. Starting from the last latest path, the second generated address is not 1

### How it should behave?

Exit the mnemonic and import it again. The address with path 0 is correct, and the cache of subsequent paths has not been cleared. Starting from the last latest path, the second generated address is not 1

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by LuizAsFight** [comment]
Interesting, we will explore it. thanks for reporting @keeplook
