### ISSUE TITLE
Explore Wallet error around DBIndexed (sentry)

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#1124]

**Comment by helciofranco** [comment]
I've been able to simulate this issue by: 
1. importing a regular wallet via seed phrase.
2. and then "clearing the site data" through the DevTools.
3. tried to imported another seed phrase.

Not sure if it's related yet, I'll come back to this later though.


![Image](https://github.com/FuelLabs/fuels-wallet/assets/7074983/e863bd93-e43d-45c6-8a39-be0f3d983c52)
