### ISSUE TITLE
fuel wallet extension doesn´t connect fuel dapps

### ISSUE THREAD

**Issue by FininhoGui** [FuelLabs/fuels-wallet#1128]
### What version of Wallet are you using?

0.15.2

### What is happening?

fuel wallet extension doesn´t connect fuel dapps. the bridge and sway farm ask me to instal the extension when i try to connect them to fuel wallet, extension already installed, its ridiculous. using edge browser

### steps to reproduce

try connect fuel wallet extension to sway farm or even the fuel bridge. it asks you to instal extension (WHAT? WHY? AGAIN?)

### How it should behave?

should just connect like every dapp with miminum development

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Other

### What is your browser version?

edge

**Comment by LuizAsFight** [comment]
@FininhoGui 

Bridge got a new release with changes to connectors. Can you check if it's working now?
make sure your wallet is up-to-date
https://app.fuel.network/

**Comment by LuizAsFight** [comment]
Closing due to lack of response
