### ISSUE TITLE
bridge

### ISSUE THREAD

**Issue by yz-ux** [FuelLabs/fuels-wallet#1130]
### What version of Wallet are you using?

fuel wallet

### What is happening?

I withdrew more than 1 eth from Sepolia to fuel, and the transaction was successful. However, I withdrew 1 eth from FUEL to Sepolia, and it has been 4 days and the account has not yet been paid.

### steps to reproduce

https://app.fuel.network/tx/0xc36ae74ba9130d4ec37f6968a7f927a0067fddbb39c14c74ee947519085a52d0

### How it should behave?

![fuel](https://github.com/FuelLabs/fuels-wallet/assets/131943400/bbabab35-1bb9-47ef-8b1e-23af2f2ce591)

### What os are you seeing the problem on?

None

### What browser?

None

**Comment by Zeeprince88** [comment]
It is taking this long currently, but working fine even switched off

**Comment by LuizAsFight** [comment]
The withdrawal process needs a last step which is relaying message on ethereum side. Did you do that ? @yz-ux

**Comment by LuizAsFight** [comment]
closing due to lack of response
