### ISSUE TITLE
Yellow warning triangle not necessary in this case

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuels-wallet#1148]
### What version of Wallet are you using?

Version: 0.15.2

### What is happening?

When connecting an app to the wallet, in this case the bridge, the wallet tells you what the app is allowed to do, in this case it gives the following list with a green tick or a red cross next to each point

(green tick) `View your account address`
(green tick) `Request transaction approval`
(green tick) `Request message signature`
(green tick) `Read your transaction history`
(red cross)  `View your private keys`

<img width="476" alt="image" src="https://github.com/FuelLabs/fuels-wallet/assets/114662397/a357940b-6651-4f16-ac8b-6ff5239b84ec">

After confirmation, a yellow triangle is is shown above the app connection box as shown in the image below

<img width="555" alt="image" src="https://github.com/FuelLabs/fuels-wallet/assets/114662397/cd6d9e28-28fd-44d9-9fc2-a032ed231562">

My assumption is that because all the points are not a green tick, then a warning is given in the form of the yellow warning triangle.

In reality, no warning is required in this case, the user should be happy that the app cannot view the private key.

### steps to reproduce

Check under ### What is happening

### How it should behave?

Generally speaking, maybe we should have a re-think on how the information should be displayed to the user.  In this case I would expect a green tick rather than a yellow warning triangle.

Maybe the last message should read:

(green tick) `Cannot view your private keys`

and then a green tick would be displayed rather than a yellow warning triangle

If there's a red cross against any of the other 4 points, namely:

`View your account address`
`Request transaction approval`
`Request message signature`
`Read your transaction history`

Then I don't think that's a problem, we should still display a green tick as an overall status.  But also conversely maybe there should be a yellow warning triangle if an app can `Read your transaction history` or `View your account address`

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Version 122.0.6261.112 (Official Build) (x86_64)

**Comment by helciofranco** [comment]
@HoTandy does that make sense?

I replaced that `warning icon` with a grey `info circle icon`.

<img width="334" alt="Screenshot 2024-03-25 at 11 42 57" src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/3dce8c76-42c9-4578-8103-03182dfdc709">
