### ISSUE TITLE
[wallet sdk] A `switchNetwork` method

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-wallet#1163]
### Motivation

Currently we do not have a `switchNetwork` method that would prompt a popup that would let users switch to a different network in the wallet.

Would be nice if we can have a counterpart React Hook for this as well.

**Comment by arboleya** [comment]
@LuizAsFight Do you think we could prioritize this?

This will help increase the experience on the dApp we generate via `create fuels` CLI.

cc @Dhaiwat10 @petertonysmith94
