### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Elp58** [FuelLabs/fuels-wallet#1184]
### What version of Wallet are you using?

hello, my wallet fuel12cphc7qx2j2cmwdd0wf7jralut6g8hjltgu4yrxhjsgcfzp3jwxshdjnzh does not connect to the site https://app.fuel.network/portal/bridge?from=eth&to=fuel

### What is happening?

hello, my wallet fuel12cphc7qx2j2cmwdd0wf7jralut6g8hjltgu4yrxhjsgcfzp3jwxshdjnzh does not connect to the site https://app.fuel.network/portal/bridge?from=eth&to=fuel     Blank screen

### steps to reproduce

hello, my wallet fuel12cphc7qx2j2cmwdd0wf7jralut6g8hjltgu4yrxhjsgcfzp3jwxshdjnzh does not connect to the site https://app.fuel.network/portal/bridge?from=eth&to=fuel

### How it should behave?

Blank screen

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

8.1

**Comment by Elp58** [comment]
Blank screen

**Comment by Elp58** [comment]
I click connect wallet, both the wallet and the bridge disappear

**Comment by LuizAsFight** [comment]
hi @Elp58 thanks for reporting. There is a release soon to come that has changes regarding connection , it may fix your problem. I will let you know

**Comment by LuizAsFight** [comment]
closing due to lack of response
