### ISSUE TITLE
Live wallet page sends to 404

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuels-wallet#1237]
### What version of Wallet are you using?

fuel-wallet-0.16.1.zip

### What is happening?

When I click to download the latest dev wallet (`fuel-wallet-0.16.1.zip`) from the page that is LIVE right now, it leads me to a `404`.

https://github.com/FuelLabs/fuels-wallet/assets/114662397/c4d01c88-beff-434e-bd5d-a210624d3369

### steps to reproduce

1. https://wallet.fuel.network/docs/install/
2. Click Download [FuelWallet zip file](https://next-wallet.fuel.network/app/fuel-wallet-0.16.1.zip)
3. 404

### How it should behave?

The file should be downloaded

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Version 123.0.6312.122 (Official Build) (arm64)

**Comment by LuizAsFight** [comment]
this is fixed already
