### ISSUE TITLE
Error in Chrome when importing latest dev wallet

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuels-wallet#1238]
### What version of Wallet are you using?

0.16.2

### What is happening?

1. Drag the zip file into chrome://extensions
2. See errors in Chrome

See screenshots and log

[import wallet.log](https://github.com/FuelLabs/fuels-wallet/files/15023452/import.wallet.log)

![Image](https://github.com/FuelLabs/fuels-wallet/assets/114662397/694ba83e-a37e-4cf4-8c5f-0bb5c2f9c8ca)

### steps to reproduce

1. Drag the zip file into chrome://extensions
2. See errors in Chrome

### How it should behave?

No errors should be seen

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Version 123.0.6312.122 (Official Build) (arm64)

**Comment by LuizAsFight** [comment]
this is fixed
