### ISSUE TITLE
User can send ETH to the same address the user is sending from

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuels-wallet#1245]
Should it be possible to send `ETH` back to the same address as shown in the video?

This is probably allowed at a protocol level but do you want to allow that in Fuel wallets, it can result in the following negative user experience:

1. The user will simply burn fees for no reason
2. The user might do this accidentally, in this case, at least a warning would be useful

https://github.com/FuelLabs/fuel-connectors/assets/114662397/f103485a-d948-4950-a500-bbd30a6cecd5

Expected behaviour:

1. Block users from being able to send assets to the same address they're sending from, or
2. Warn users that they're about to send assets to the same address they're sending from

**Comment by LuizAsFight** [comment]
I don't think we should fix this as:
- protocol allows you to send to yourself
- wallet is clearly showing "From" and "To" as the same account
