### ISSUE TITLE
Account name case sensitivity

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuels-wallet#1263]
### What version of Wallet are you using?

dev Version: 0.16.2

### What is happening?

- I have 2 accounts in my wallet, I go to change the name of one of the accounts, I want to make the first letter of the word upper case rather than lower case.
- If I delete the letter `w` and replace it with `w`, there's an error message stating the name is already in use.
- If I delete the letter `w` and replace it with `W`, there's no error message and the wallet allows me to click Confirm
- Clicking `Confirm` produces an error message stating `Account Name Already Exists`
- Clicking `Confirm` again shows no error message, as if the first click crashed the wallet (but I don't think it did)
- See video below to support the explanation above

https://github.com/FuelLabs/fuels-wallet/assets/114662397/9e11b868-1f20-47e6-a9f0-0952d4796bdf

### steps to reproduce

See above and video attached

### How it should behave?

- The backend of the wallet name change functionality seems to be case insensitive as I cannot simply change a letter from lower case to upper case, it thinks the name is the same word
- The frontend however spots it's a different name and doesn't show this on the wallet screen when I change a letter in the name to upper case rather than lower case

- The frontend and back end should be consistent
- Decide whether the naming conventions should be case sensitive or not, I believe it should be 

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Version: 0.16.2

**Comment by BlackEyesForThree** [comment]
Additional explanation: The duplicate wallet name was modified again after encountering error messages, but no error messages were found
