### ISSUE TITLE
Add copy button to error feedback

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#1303]
in the TxContent component, we have a error feedback header that can show up.

we should add a copy button to it allowing the user to copy the stringified error

**Comment by ameeetgaikwad** [comment]
would like to contribute! 
@arthurgeron if you haven't started, do you mind if i go ahead?

**Comment by LuizAsFight** [comment]
@ameeetgaikwad thanks ! yes you can check this one
