### ISSUE TITLE
create `staging` website with chrome store wallet

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#1320]
for all versions 
- remove the top-right "Install Wallet" button

wallet.fuel.network:
- the official doc of "Fuel Wallet"
- should not contain link to zip file, instead it can have a link for the `staging-wallet` and `next-wallet`

staging-wallet.fuel.network
- this version should be created, we don't have yet
- it should be released when push code to `staging` branch
- the doc of "Fuel Wallet Development"
- should be able to download the zip file, as-is now, (need to download from staging-... instead of next-...)

next-wallet.fuel.network
- should not have link to chrome store
- should be able to download the zip file, as-is now

**Comment by arthurgeron** [comment]
@LuizAsFight Branch `staging` created, we just need to apply branch protection rules to it (e.g. no force-push, no deletion, etc)
