### ISSUE TITLE
Learn more link broken

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#1387]
in the connect screen, the learn more link is broken:
1- hard to click, needs to hover on top part of text
2- when you click, it redirects you to home page.

![Image](https://github.com/FuelLabs/fuels-wallet/assets/8636507/b5a7a8f0-e942-4ad4-9041-52f71df03eb6)

**Comment by Spiral-Memory** [comment]
Hey @LuizAsFight 

I have raised a PR addressing the issue you mentioned. Kindly review the PR. As I am a first-time contributor to this repo, please let me know if I have done everything correctly. I will make the required changes if necessary.
