### ISSUE TITLE
Transaction history bug

### ISSUE THREAD

**Issue by apexdevtest** [FuelLabs/fuels-wallet#1413]
### What version of Wallet are you using?

0.22.0

### What is happening?

Can not see transactions history.
![Screenshot_10](https://github.com/FuelLabs/fuels-wallet/assets/97692805/5166a615-b3e2-43eb-a4d2-568b111c54eb)

### steps to reproduce

watch transactions history

### How it should behave?

It should show transactions list

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

126.0.6478.127 (Official Build) (64-bit)

**Comment by apexdevtest** [comment]
//Bug codes below 

{
  "error": {
    "VERSIONS": {
      "FORC": "0.59.0",
      "FUEL_CORE": "0.26.0",
      "FUELS": "0.88.1"
    },
    "metadata": {},
    "code": "parse-failed",
    "name": "FuelError"
  },
  "reactError": {
    "componentStack": "\n    at gS (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:396:47893)\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:334:18705\n    at qf (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:396:49909)\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:334:18705\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:334:18705\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:399:19398\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:334:18705\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:334:18705\n    at main\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:334:18705\n    at Ne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:399:19587)\n    at Vme (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:396:50161)\n    at Eae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:3759)\n    at Eae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:3759)\n    at bh (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:6323)\n    at Lj (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:397:7938)\n    at Eae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:3759)\n    at bh (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:6323)\n    at zj (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:399:25070)\n    at Hj (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:399:25212)\n    at T1e\n    at Eae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:3759)\n    at DE (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:6949)\n    at Vae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:373:6494)\n    at t (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:373:8911)\n    at qme (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:397:1640)\n    at koe (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:342:2393)\n    at b0e (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:399:25814)\n    at q1e\n    at Pae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:364:6383)\n    at Rae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:373:419)\n    at E0e (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-a5f55bd7.js:399:27286)"
  },
  "timestamp": 1720624455498,
  "id": "d2c3f1ff-12ef-4e7d-bb31-4d379f3bdf25",
  "location": "chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/popup.html#/transactions",
  "pathname": "/popup.html",
  "hash": "#/transactions"
}

**Comment by LuizAsFight** [comment]
ty for reporting. this is fixed can you test again?
