### ISSUE TITLE
Service instance not correct after some iterations 

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#144]
### What version of Wallet are you using?

0.0.1

### Steps to Reproduce

1- Create a machine

2- in a hook, instantiate it with `store.useService`
```
const service = store.useService(Services.account);
```

3- create an dynamic action from the hook (i.e `onDoneUnlocking`)
```
  store.useSetMachineConfig(Services.account, {
    actions: {
      onDoneUnlocking(ctx, event) {
        // any action
      },
    },
  });
```

4- execute a service that changes the context as a result, and fire the dynamic action created `onDoneUnlocking`
```
unlocking: {
        invoke: {
          src: 'unlock',
          data: {
            input: (_: MachineContext, ev: MachineEvents) => ev.input,
          },
          onDone: [
            {
              actions: ['assignWallet', 'onDoneUnlocking'],
              target: 'done',
            },
          ],
        },
      },
```

5- from the `onDoneUnlocking` action, send an event to the machine. 
```
service.send('SIGN_MESSAGE', { input: { message } });
```

6- in the machine, listen to `SIGN_MESSAGE` and invoke a service that needs to use the context.
```
signingMessage: {
        invoke: {
          src: 'signMessage',
          data: {
            input: (_: MachineContext, ev: MachineEvents) =>{
              console.log(`_`, _);
              // context will be wrong.
            },
          },
```

### Expected Behavior

context data should be right

### Actual Behavior

context data is not right

**Comment by luizstacio** [comment]
@LuizAsFight I think this is already fixed correct?

**Comment by LuizAsFight** [comment]
probably not, @pedronauck did some fixes but not related to this issue I think, right @pedronauck ?

might be fixed as side-effect of other changes, but need to test again

**Comment by LuizAsFight** [comment]
I tested here and this bug is fixed.
