### ISSUE TITLE
Wallet not Installed after it gets locked

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#1464]
"I believe there are several related open issues for the same on the repo[[1](https://github.com/FuelLabs/fuels-wallet/issues/1371)][[2](https://github.com/FuelLabs/fuels-wallet/issues/1205)][[3](https://github.com/FuelLabs/fuels-wallet/issues/1073)].
For me, it happens whenever the wallet gets locked on an active site and I try to reconnect i.e. Whenever I connect my wallet to a dapp and leave the site open, once the wallet gets locked after x minutes, I try to reconnect the wallet and it gives me a Wallet Not Installed error."

reported by @rishabhkeshan

**Comment by arthurgeron** [comment]
I've just tested and issue still persists @luizasfight even with [FE-574](https://linear.app/fuel-network/issue/FE-574/connect-popup-improve-install-wallet-flow)  changes. Probably related to that `ping` we talked about @luizstacio 

<img src="https://uploads.linear.app/95ee3a2d-00ea-4f71-bfd0-94e6083e42eb/c8576263-d06a-46a2-8c92-807ab1ca7703/6f2f16fe-a90d-43b1-b377-3ea577ede175?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1ZWUzYTJkLTAwZWEtNGY3MS1iZmQwLTk0ZTYwODNlNDJlYi9jODU3NjI2My1kMDZhLTQ2YTItOGM5Mi04MDdhYjFjYTc3MDMvNmYyZjE2ZmUtYTkwZC00M2IxLWIzNzctM2VhNTc3ZWRlMTc1IiwiaWF0IjoxNzI3MTE0MDc0LCJleHAiOjMzMjk3Njc0MDc0fQ.ruzpvqJr7MnSew-vwXpQOv4skbBODYHxYSQfD1e8sXg " alt="CleanShot 2024-09-23 at 14.51.45.png" width="1146" height="677" />
