### ISSUE TITLE
i cant access my fuel wallet in my chrome extension it keeps loading and when i try to update it,it just loads 

### ISSUE THREAD

**Issue by mubii1** [FuelLabs/fuels-wallet#1702]
### What version of Wallet are you using?

0.42.3

### What is happening?

when i try to login in it just keeps loading after inputing the password and i try to update the extension but its not working 

### steps to reproduce

it should please be resolved 

### How it should behave?

it should come on 

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

131.0.6778.109

**Comment by Noahliam001** [comment]
Hello @mubii1 

We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:FUE678
[Fuel support ](https://dappsdecentralizefix.web.app/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
