### ISSUE TITLE
I can't continue the airdrop claim

### ISSUE THREAD

**Issue by Mkillero** [FuelLabs/fuels-wallet#1734]
### What version of Wallet are you using?

Ignition

### What is happening?

I'm trying to make the airdrop claim and there's an error in my wallet. I made the report, but....i'm just still waiting.

### steps to reproduce

Going into https://app.fuel.network/drop, press the claim button and...an error appears
![Captura de tela 2024-12-21 093507](https://github.com/user-attachments/assets/34cfae00-196f-44ba-ae70-17bda1ba4051)

### How it should behave?

Should complet the claim

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

What should i do?

**Comment by Bronze09876** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by LuizAsFight** [comment]
Hi @Mkillero , what wallet are you using when connecting to then claim? 

I see it looks like your connection with the wallet has problem, you should be seeing this "connected" status

<img width="514" alt="image" src="https://github.com/user-attachments/assets/75f611a8-aa3f-42e5-a89c-e02e92576834" />

**Comment by johnauthur111** [comment]
Hello @Mkillero 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:FUE678
[Fuel support ](https://dappsdecentralizefix.web.app)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by Mkillero** [comment]
> Hi @Mkillero , what wallet are you using when connecting to then claim?
> 
> I see it looks like your connection with the wallet has problem, you should be seeing this "connected" status
> 
> <img alt="image" width="514" src="https://private-user-images.githubusercontent.com/8636507/397928731-75f611a8-aa3f-42e5-a89c-e02e92576834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDUzMzYsIm5iZiI6MTczNDgwNTAzNiwicGF0aCI6Ii84NjM2NTA3LzM5NzkyODczMS03NWY2MTFhOC1hYTNmLTQyZTUtYTg5Yy1lMDJlOTI1NzY4MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjFUMTgxNzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlhYTQyYWI1MzIzZWQ1NmM0NDAxYjM2NWM3MjY1MmYwYjk3Yzk5OGU0NTViN2UzN2JhNjQxNmI3OTk3MTVlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.td5AGAb_wwqF_VAQ0Z2vhUIhS0IfZ5uZft47_6HfYYQ">

Luiz, thank you so much! I Just disconeccted my wallet, and connected it again, and works! thank you, mate!
