### ISSUE TITLE
Wallet SDK integration with Fuels-ts SDK

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#175]
On the part of creating transactions, providers, etc. We have to discuss exposing methods for all things like querying data from providers, passing a contract, and func, args, txParams, and more to make contract calls, etc. This is good from the viewpoint of control but we lose flexibility and disconnect Fuels-ts SDK from the Wallet Extension. 

The option I'm going to suggest is a similar approach to the current market designs. By adding a new Wallet Signer type on Fuels-ts SDK that integrates with the Wallet Extension in this way;

- All public provider calls can go directly from the client to the network provider.
- All features implemented on the SDK will work as they are today.
- When the client tries to send a transaction that needs to be signed, the Wallet Extension will be prompted and submitted via the wallet. Or anything that requires a signature.
- One issue is network differences, as the app can query things from one provider, and the wallet is connected to another. This issue can be improved but never fixed, as the developer can use the Graphql API directly from the client. Also, if we have some kind of chainId in the future will make this problem irrelevant.

**Comment by arboleya** [comment]
WRT network differences, couldn't we share the wallet `provider` with the SDK?

**Comment by luizstacio** [comment]
> WRT network differences, couldn't we share the wallet `provider` with the SDK?

The URL of the provider would be shared, but the requests can happen on both side, on the SDK and on the Wallet

**Comment by arboleya** [comment]
Would that be different if we'd share the actual `provider` **instance**? _(not just the URL)_

**Comment by luizstacio** [comment]
> Would that be different if we'd share the actual `provider` **instance**? _(not just the URL)_

It would not be possible as the website runs in an isolated env from the wallet. They communicate through messages.
