### ISSUE TITLE
Create Accounts screen

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/fuels-wallet#20]
## Tasks
- [ ] Create show/hidden toggle on list

## Blocked by
- #21

**Comment by luizstacio** [comment]
@matt-user  For now, we are going to defer the implementation of the search bar.

**Comment by matt-user** [comment]
> @matt-user For now, we are going to defer the implementation of the search bar.
I don't see a search bar in the v1 figma, but thanks for the info!
