### ISSUE TITLE
macOS unlock screen too big when in fullscreen

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#201]
### What version of Wallet are you using?

0.0.1

### Steps to Reproduce

Unlock screen is too big when on fullscreen

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/8636507/201762251-a1a7c207-be33-4223-8977-4d982637b3fe.png">

### Expected Behavior

fullscreen should respect app box size

### Actual Behavior

it's not respecting app box size

**Comment by oniks68** [comment]
it's the same for me! Password must be entered again each time; rather just once)

**Comment by LuizAsFight** [comment]
@oniks68 

this issue will change unlock flow to ask password only once per session...
https://github.com/FuelLabs/fuels-wallet/issues/244
