### ISSUE TITLE
Typo in Sign Up

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-wallet#207]
Instead of "Write down your Recover Phrase" it should be "Write down your Recovery Phrase"

**Comment by shabai98** [comment]
Very good working

**Comment by DyaconF** [comment]
very smooth transaction no bug. I joined its testnet beta 2, it is a very secure wallet. And its transection is completed very fast, I'm really lucky to be able to use the fuel wallet fuel199hg3h79xlg8txdcupz4j5qn5gjnrxu0at8p8uup39eakzzk88xs4x2445
