### ISSUE TITLE
Create AccountList component

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/fuels-wallet#21]
## Figma Reference
https://www.figma.com/file/uEckQY4EaQ5rXwyISg6d1g/Fuel-Wallet?node-id=290%3A16182

## Props
- `items: Account[]`

## Subcomponent
- `<AccountList.Loading />`
  - This is just a loading state using our Skeleton

**Comment by luizstacio** [comment]
For now we are going to defer the implementation of search bar.

**Comment by matt-user** [comment]
This component already exists, although I'm not sure what commit it was added to master
