### ISSUE TITLE
Abnormal faucet

### ISSUE THREAD

**Issue by playweta** [FuelLabs/fuels-wallet#214]
### What version of Wallet are you using?

changeset-release/meta --- dev0.01

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/47896870/202150436-34163ef0-7e03-4231-8fa9-fa343186c19c.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/47896870/202150475-be0d5b35-16ed-4bc4-9c31-bdb65f5b47d5.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/47896870/202150486-48dee5ec-c2ed-4e24-b6cd-eeee4ac398c1.png)

**Comment by luizstacio** [comment]
We had a small issue with the captcha server connection, it should work now.
