### ISSUE TITLE
Faulty send button

### ISSUE THREAD

**Issue by coat78** [FuelLabs/fuels-wallet#215]
### What version of Wallet are you using?

Latest version downloaded today 

### Steps to Reproduce

Install the file from githhub create account verify seed and close tab then reopen again to access wallet hit send button nothing happens but recieve works just fine

### Expected Behavior

It is supposed to pop up a send page to input receiver address 

### Actual Behavior

Did not respond when clicked

**Comment by luizstacio** [comment]
This screen is not implemented yet: #39

Thanks for reporting
