### ISSUE TITLE
"Send is not implemeted yet"

### ISSUE THREAD

**Issue by JubileGus** [FuelLabs/fuels-wallet#218]
### What version of Wallet are you using?

0.0.1

### Steps to Reproduce

Click SEND.

### Expected Behavior

Wanted to send some test tokens to other tester.

### Actual Behavior

Simply can't send tokens. Once SEND is clicked "Send is not implemeted yet" pops up. Other people are sending tokens, so thats why im reporting. Also word "implemented" is misspelled

**Comment by luizstacio** [comment]
Send is not developed yet you can track it here #39. You can also check the list of features that are missing but will be developed on the readme: https://github.com/FuelLabs/fuels-wallet#features
