### ISSUE TITLE
Blank tab confirmation in browser android

### ISSUE THREAD

**Issue by hendrikmichael** [FuelLabs/fuels-wallet#220]
### What version of Wallet are you using?

Last version your wallet

### Steps to Reproduce

i tried to do it in android browser.  after clicking connect.  confirmation tab appears but blank no action.  I think this needs to be fixed in the future.  thanks
![Screenshot_2022-11-18-00-11-10-116_com kiwibrowser browser](https://user-images.githubusercontent.com/57870748/202518654-fa72b2b0-0005-48d0-aa54-63885a208b32.jpg)

### Expected Behavior

I hope fix your bug

### Actual Behavior

Problem tab confirmation open with android browser

**Comment by luizstacio** [comment]
We currently do not support the android browser, but we look forward to fixing it.
