### ISSUE TITLE
Wallet crashes if there is a typo in secret phrase

### ISSUE THREAD

**Issue by RetiArn** [FuelLabs/fuels-wallet#221]
### What version of Wallet are you using?

Fuel Wallet 0.0.1

### Steps to Reproduce

Do a typo in one of the last few secret phrase words, and not correct it fast.

### Expected Behavior

Complete creation of a wallet

### Actual Behavior

When type is in one of the last 2 mnemonic phrases words, wallet crashes, and you need to start over. If you are fast enough it is possible to correct it and complete the process.

**Comment by luizstacio** [comment]
Related to #281
