### ISSUE TITLE
Connection approval 

### ISSUE THREAD

**Issue by Peters6444** [FuelLabs/fuels-wallet#222]
### What version of Wallet are you using?

The provided version on github

### Steps to Reproduce

https://fuels-wallet.vercel.app/#/dapp refuse to connect to Fuel wallet 

### Expected Behavior

Expect approval tab to open automatically 

### Actual Behavior

Approval tab refuse to pop up

**Comment by luizstacio** [comment]
Could you try with the current documentation application to see if the error persists?
