### ISSUE TITLE
PopUp not opened!

### ISSUE THREAD

**Issue by erlando666** [FuelLabs/fuels-wallet#225]
### What version of Wallet are you using?

Fuel Wallet 0.0.1

### Steps to Reproduce

i tried several platforms like https://fuels-wallet.vercel.app/#/dapp and I can't connect to my wallet.

### Expected Behavior

i think the team can solve easily with this bug

### Actual Behavior

PopUo can't opened in my wallet extension.

**Comment by luizstacio** [comment]
Thanks for the report, Can you add more details?

What browser are you using?
What version of the browser?
And What platform?

**Comment by erlando666** [comment]
I use an Android device and use the browser mises extension.

Pada tanggal Sel, 22 Nov 2022 15.53, Luiz Estácio | stacio.eth <
***@***.***> menulis:
