### ISSUE TITLE
Send is not implemeted yet

### ISSUE THREAD

**Issue by x-felix-01** [FuelLabs/fuels-wallet#228]
### What version of Wallet are you using?

0.0.1

### Steps to Reproduce

.

### Expected Behavior

.

### Actual Behavior

.

**Comment by luizstacio** [comment]
The send function is not implemented yet, you can track it here #39. You can also check the list of the missing features that will be developed on our readme: https://github.com/FuelLabs/fuels-wallet#features Thanks.
