### ISSUE TITLE
Add validation on input amount test page

### ISSUE THREAD

**Issue by imblackjack1** [FuelLabs/fuels-wallet#229]
### What version of Wallet are you using?

i dont konw

### Steps to Reproduce

When the decimal point of the transfer amount exceeds 10 digits, the transfer button does not respond

### Expected Behavior

When the decimal point of the transfer amount exceeds 10 digits, the transfer button does not respond

### Actual Behavior

When the decimal point of the transfer amount exceeds 10 digits, the transfer button does not respond

**Comment by luizstacio** [comment]
The current test page doesn't have validations to control the number of max digits that are causing an error.

**Comment by luizstacio** [comment]
Issue #323 will add validation on the input to fix this issue.
