### ISSUE TITLE
Wallet Mag

### ISSUE THREAD

**Issue by NeGaTiVeSTE** [FuelLabs/fuels-wallet#231]
### Motivation

I think u need wallet manager in wallet, for example i wanna create  2 or 3 wallets, will be fine if u realise it.

### Usage example

For example, 1 wallet will be only for my funds and actually if i will get scam , i dont  lose all my money

### Possible implementations

![image](https://user-images.githubusercontent.com/118696032/202930672-0dbedd2b-c4a5-41df-8a54-7eba27a9e4a1.png)

Will be fine create bottom "create new wallet" here.

**Comment by luizstacio** [comment]
We are working to support multiple accounts soon, you can track these issues: https://github.com/FuelLabs/fuels-wallet/issues/20 https://github.com/FuelLabs/fuels-wallet/issues/21 https://github.com/FuelLabs/fuels-wallet/issues/22. You can also check the list of features that are missing but will be developed on the readme: https://github.com/FuelLabs/fuels-wallet#features
