### ISSUE TITLE
Wallet not ask for password 

### ISSUE THREAD

**Issue by capknsedat** [FuelLabs/fuels-wallet#234]
### What version of Wallet are you using?

0.0.1

### Steps to Reproduce

if in chorome u install and from windows if u did restart when u open chrome and wallet its not asking a password

### Expected Behavior

after every enter have to ask password

### Actual Behavior

password have to ask also u cant see seed words

**Comment by luizstacio** [comment]
Can you clarify this issue? improve description and title? It looks to be talking about two different things, add a feature to lock automatically that can be related to this: #244 and also reveal seed phrase #25.
