### ISSUE TITLE
Asking to fill the password anytime

### ISSUE THREAD

**Issue by rendyan112** [FuelLabs/fuels-wallet#237]
### What version of Wallet are you using?

0.0.1

### Steps to Reproduce

![Uploading Screenshot 2022-11-22 125513.png…]()

### Expected Behavior

when you want to confirm a transaction it always asks for a password, that's very annoying in my opinion.

### Actual Behavior

please remove this feature just once asking for a password.

**Comment by luizstacio** [comment]
Closing in favor of: https://github.com/FuelLabs/fuels-wallet/issues/244
