### ISSUE TITLE
I got an issue on "Approve Transaction , Confirm transaction" . 

### ISSUE THREAD

**Issue by namnguyenetsy** [FuelLabs/fuels-wallet#238]
### What version of Wallet are you using?

latest version

### Steps to Reproduce

Approve Transaction -> Confirm transaction . 

### Expected Behavior

It didn't appear the popup to confirm transaction . 

### Actual Behavior

It didn't appear the popup to confirm transaction .

**Comment by luizstacio** [comment]
Can you provide what platform are you using?

**Comment by pedronauck** [comment]
Closed since there was no answer here, fell free to reopen.
