### ISSUE TITLE
Add "Add account/wallet" option .

### ISSUE THREAD

**Issue by namnguyenetsy** [FuelLabs/fuels-wallet#241]
### Motivation

Hello people .
I'm wondering if you can add "Add account/wallet" option .

**Comment by luizstacio** [comment]
We already have this on our roadmap thanks for reporting. #20 #21 #22 you can also check the list of features that are missing but will be developed on the readme: https://github.com/FuelLabs/fuels-wallet#features

**Comment by namnguyenetsy** [comment]
> We already have this on our roadmap thanks for reporting. #20 #21 #22 you can also check the list of features that are missing but will be developed on the readme: https://github.com/FuelLabs/fuels-wallet#features

I see . Thank you bro .
