### ISSUE TITLE
Update unlock flow, to request password once per session

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#244]
Currently, the wallet asks for users a password every time the user is required to sign a transaction or message.

We should move it to a session and manage the global state; once the user unlocks the wallet, we start a session that auto-closes after a configured period. Default (~5min).

**Comment by luizstacio** [comment]
We need to make sure the state is live only on memory. This will require moving the access of the signature to the service worker.

**Comment by pedronauck** [comment]
I'm working in a solution for this already
