### ISSUE TITLE
Send is not implemeted yet 

### ISSUE THREAD

**Issue by 0xserok** [FuelLabs/fuels-wallet#248]
### What version of Wallet are you using?

Testnet beta-2

### Steps to Reproduce

send is not yet implemeted

### Expected Behavior

activating the submit button

### Actual Behavior

I get a message that send is not yet implemented

**Comment by luizstacio** [comment]
Currently, the send operation is not implemented this is going to be implemented soon: https://github.com/FuelLabs/fuels-wallet/issues/39
