### ISSUE TITLE
Send button is not working

### ISSUE THREAD

**Issue by Ckaarraa** [FuelLabs/fuels-wallet#256]
### What version of Wallet are you using?

Last version 24.11.2022

### What is happening?

Send button is not working

### steps to reproduce

I tried it different browsers but not.

### How it should behave?

It could send asset.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Last

**Comment by lzweth** [comment]
the send button is unavailable temporarily
try more features here (sign and transfer)
https://fuels-wallet.vercel.app/#/dapp

**Comment by lzweth** [comment]
Hi, send feature is not launched yet, you can see all features here - https://github.com/FuelLabs/fuels-wallet#features

**Comment by luizstacio** [comment]
@lzweth, thanks for answering. I'm just confirming that currently, send operation is not implemented this is going to be implemented soon: [#39](https://github.com/FuelLabs/fuels-wallet/issues/39). You can also check our features roadmap on the readme to track our features: https://github.com/FuelLabs/fuels-wallet#features
