### ISSUE TITLE
Faucet issue 

### ISSUE THREAD

**Issue by Riyazkhanridao** [FuelLabs/fuels-wallet#257]
### What version of Wallet are you using?

0.0.1

### What is happening?

When i claim faucet he didn't work properly and he tell again and again failed error please solve this issue as soon as possible 

### steps to reproduce

All good 

### How it should behave?

Faucet claim issue

**Comment by luizstacio** [comment]
This error is on our faucet project. We are currently working to improve it. You can keep track of the faucet repo https://github.com/FuelLabs/faucet/.
