### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by afsinkoroglu** [FuelLabs/fuels-wallet#258]
### What version of Wallet are you using?

fuel

### What is happening?

I couldn't use send button.my wallet adress is fuel1cwlaqupmwsmu42km2l8l6s7w3ef76v4kxzuraszc3t28w4v0035sut2qdh

### steps to reproduce

![fuel bug](https://user-images.githubusercontent.com/108057446/203983625-7660598a-7314-4fc0-9edd-1423af353c73.png)

### How it should behave?

![fuel bug](https://user-images.githubusercontent.com/108057446/203983808-d1b95ea9-5ea7-495e-a237-3d549391ab35.png)

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Other

### What is your browser version?

microsoft edge the last version

**Comment by lzweth** [comment]
As the prompt window says, the send feature is not yet available. With the upgrade, there will be more and more features, you can check the features currently available for the wallet here. https://github.com/FuelLabs/fuels-wallet#features
