### ISSUE TITLE
Popup not opened!

### ISSUE THREAD

**Issue by 0xSaubhagya** [FuelLabs/fuels-wallet#259]
### What version of Wallet are you using?

Beta 2

### What is happening?

i connected to fuel wallets dapp- https://fuels-wallet.vercel.app/#/dapp and clicked on "Connect" to connect the fuel wallet a pop came but it doesn't open
![Screenshot_2022-11-25-20-20-59-202_com kiwibrowser browser](https://user-images.githubusercontent.com/119060982/204013097-eb07a816-1b38-4142-b773-fa57589b2f8e.jpg)

### steps to reproduce

![Screenshot_2022-11-25-20-20-59-202_com kiwibrowser browser](https://user-images.githubusercontent.com/119060982/204014968-cb0b3053-9e59-4833-8bc6-ef9993897d53.jpg)

### How it should behave?

Should open the popup to connect with Fuel wallet.

### What os are you seeing the problem on?

Android Mobile

### What browser?

Other

### What is your browser version?

Kiwi Browser Version 107.0.5304.74

**Comment by lzweth** [comment]
it doesn't currently work on Android because it hasn't been tested on mobile devices. You need to test it on PC.
