### ISSUE TITLE
Wallet Conntection

### ISSUE THREAD

**Issue by Slayssss** [FuelLabs/fuels-wallet#260]
### What version of Wallet are you using?

0.0.1

### What is happening?

I tried to connect vercel app for test transaction.
But when I clicked "connect" -> opened another tab with page contains "/popup.html#/request/connection" end point. Not in extension, I also tried to open fuel extension for check any requests, but didnt see, only main page with my address and balance.

So, Page without any button for signature 
![image](https://user-images.githubusercontent.com/65529374/204071088-54ebef2f-93a1-456c-a6b2-6df6b889e1f4.png)

Next step - I open the html code for this page and tried to find any buttons, and I saw 4 buttons by xpath path : "//button"
And When I move to third button  - the buttons appeared

### steps to reproduce

1. Download fuel extension
2. Register a new account
3. Receive tokens by faucet 
4. Open https://fuels-wallet.vercel.app/#/dapp
5. Click on "Connect" button

### How it should behave?

I was expecting an extension to open with a request to sign a message to connect to the site

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by luizstacio** [comment]
We have tested using the env, the pup opens as expected, and the buttons are shown correctly.
<img width="292" alt="Screenshot 2022-11-26 at 11 40 49" src="https://user-images.githubusercontent.com/3941923/204106392-f137211d-1712-4fb2-86b8-33d8673debb8.png">
