### ISSUE TITLE
Can't send anything from wallet

### ISSUE THREAD

**Issue by niloy9** [FuelLabs/fuels-wallet#261]
### What version of Wallet are you using?

Chrome extension 

### What is happening?

It says sending token or coin is not implement yet.
![Screenshot_2022-11-27-17-11-40-906_com kiwibrowser browser](https://user-images.githubusercontent.com/82341708/204132143-effa0458-bab4-43e3-b9e2-c5ea81b82a5b.jpg)

Wallet address is : fuel18d8euysnw0swl2zdgral6xq067h8vpf2vv5djnnrlt7rk6fnff0qfgpewm

### steps to reproduce

I remove and unistall my extension and download it Again and try again but it will the same problem. 
![Uploading Screenshot_2022-11-27-17-11-40-906_com.kiwibrowser.browser.jpg…]()

Wallet address is : fuel18d8euysnw0swl2zdgral6xq067h8vpf2vv5djnnrlt7rk6fnff0qfgpewm

### How it should behave?

It should work smoothly and send what i want to send. 
Wallet address is : fuel18d8euysnw0swl2zdgral6xq067h8vpf2vv5djnnrlt7rk6fnff0qfgpewm

### What os are you seeing the problem on?

Android Mobile

### What browser?

Chrome

**Comment by luizstacio** [comment]
Currently, the send operation is not implemented this is going to be implemented soon: [#39](https://github.com/FuelLabs/fuels-wallet/issues/39). You can also check our features roadmap on the readme, to track when is implemented: https://github.com/FuelLabs/fuels-wallet#features
