### ISSUE TITLE
After i made some swaps from ETH to DAI wallet says that i still have 0,5 ETH 

### ISSUE THREAD

**Issue by Citizen1337** [FuelLabs/fuels-wallet#262]
### What version of Wallet are you using?

0.0.1

### What is happening?

After i made some swaps from ETH to DAI wallet says that i still have 0,5 ETH but there and after i tried to send some crypto im pool, thing in right bottom corner says i did that but i cant see my liquidity positions (it happened before a couple attempts i thimk it can be my internet issue, everything is ok after a few attempts, but wallet still says i have 0.5 ETH )) 

### steps to reproduce

make swaps, set some pool positions

### How it should behave?

I expected that wallet will show the real number of ETH i have rn and liquidity set in my first attempt

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

107.0.5304.121

**Comment by Citizen1337** [comment]
> ### What version of Wallet are you using?
> 0.0.1
> 
> ### What is happening?
> After i made some swaps from ETH to DAI wallet says that i still have 0,5 ETH but there and after i tried to send some crypto im pool, thing in right bottom corner says i did that but i cant see my liquidity positions (it happened before a couple attempts i thimk it can be my internet issue, everything is ok after a few attempts, but wallet still says i have 0.5 ETH ))
> 
> ### steps to reproduce
> make swaps, set some pool positions
> 
> ### How it should behave?
> I expected that wallet will show the real number of ETH i have rn and liquidity set in my first attempt
> 
> ### What os are you seeing the problem on?
> Windows Desktop
> 
> ### What browser?
> Chrome
> 
> ### What is your browser version?
> 107.0.5304.121

my wallet is fuel1jyupyf58hmpf7treupfnl4thzlfqyyva76nrrwh5m8ptwypg3k5scsj57z <3

**Comment by luizstacio** [comment]
The current SwaySwap application is not using the Fuel Wallet extension, and because of this, it not's open the approval screen.
