### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Valorous1** [FuelLabs/fuels-wallet#264]
### Motivation

It is not very convenient to write a password every time you need to confirm a transaction

### Possible implementations

For example, to make a choice: you can enter the password 1 time when you enter the wallet and continue to sign transactions without a password or every time as it is now, as it will be more convenient for anyone

**Comment by luizstacio** [comment]
We have mapped to change it to a single unlock screen, on the moment you open the Wallet. You can keep track of this here: #244
