### ISSUE TITLE
creating multiple wallets inside a wallet

### ISSUE THREAD

**Issue by seione2022** [FuelLabs/fuels-wallet#265]
### Motivation

I wanted to check the speed of transactions when transferring from wallet to wallet. I had to ask a friend for an address in order to send him test tokens. It would be more convenient to throw it to yourself in order to check and not involve outsiders in the process.
P.S. Transactions go quickly, which pleases.

**Comment by luizstacio** [comment]
Thanks for the issue. We already have this on our roadmap thanks for reporting. https://github.com/FuelLabs/fuels-wallet/issues/20 https://github.com/FuelLabs/fuels-wallet/issues/21 https://github.com/FuelLabs/fuels-wallet/issues/22 you can also check the list of features that are missing but will be developed on the readme: https://github.com/FuelLabs/fuels-wallet#features
