### ISSUE TITLE
When using DApp the amount of coins didn't change

### ISSUE THREAD

**Issue by SP30-star** [FuelLabs/fuels-wallet#268]
I noticed one oddity, the number of test Ethereum coins in the wallet itself has not decreased...although I tested the exchange of test coins, added to the liquidity pool many times, the test coins of Ethereum did not decrease. I noticed one oddity, the number of test Ethereum coins in the wallet itself has not decreased...although I tested the exchange of test coins, added to the liquidity pool many times, the test coins of Ethereum did not decrease. Exchanges and adding to the liquidity pool were also not displayed in the explorer. Is this how it should be?
![1](https://user-images.githubusercontent.com/118686847/204308073-59cd0781-6051-4470-96ba-2a2acc492ee4.png)
![2](https://user-images.githubusercontent.com/118686847/204308099-f71a9ba1-9231-4a23-a411-9126765e1320.png)

**Comment by luizstacio** [comment]
Are you talking about the swayswap? If yes, the wallet is not the same. SwaySwap has an embedded wallet and not uses the wallet extension.

**Comment by luizstacio** [comment]
Thanks for the issue, Closing in favor of #312.
