### ISSUE TITLE
Bug with seed phrase if type it manually

### ISSUE THREAD

**Issue by cepdy4ek27** [FuelLabs/fuels-wallet#281]
### What version of Wallet are you using?

0.0.1

### What is happening?

While registering a wallet, if I enter the seed phrase manually, then at the 12th word the system does not wait until I end it and gives an error that the phrase is not correct. After that - the page is updated and then I see a gray screen with no buttons.

If use Copy-Paste for 12 words at the beggining - it works correct

### steps to reproduce

1. Create new wallet
2. Try to type all 12 words of seed phrase manually, if not use Copy-paste function.
3. On the 12th word, system don't give you to finish your 12th word and displayed error. 
4. The page is automatically updated and user get gray screen with no buttons.

### How it should behave?

It should behave as always on other wallets. Type 12 words, button "Confirm".

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

107.0.5304.110

**Comment by luizstacio** [comment]
Thanks for the report, I have tested it and was able to emulate it.

https://user-images.githubusercontent.com/3941923/205221831-681b67c2-e938-4675-a694-b9c631e21893.mp4
