### ISSUE TITLE
Transaction Fee Visibility

### ISSUE THREAD

**Issue by dvzico** [FuelLabs/fuels-wallet#282]
### What version of Wallet are you using?

0.0.1

### What is happening?

The transaction fee is not fully visible even when stretching the browser expansion window. Chrome on Xubuntu 22.04.1 LTS
![Screenshot_2022-11-30_17-30-51](https://user-images.githubusercontent.com/39378470/204825851-93ee602c-9e18-428a-a264-12efd67915c7.png)

### steps to reproduce

send an asset to another wallet

### How it should behave?

The fee should be fully visible with the default window size and when it is scaling

### What browser?

Chrome

### What is your browser version?

Version 107.0.5304.121 (Official Build) (64-bit)

**Comment by LuizAsFight** [comment]
@dvzico are you able to scroll ? you're supposed to be

if no scroll is working then it's a bug, otherwise it's an improvement (welcomed btw)

**Comment by luizstacio** [comment]
@dvzico can you confirm the scroll is working?

**Comment by dvzico** [comment]
Hi Luis!

Yes, scrolling helps to see all the details of the transaction in the
pop-up window of the extension, including fee and total. My question was
about the ability to completely refuse scrolling when manually stretching
the pop-up window, so that the data automatically fit to the screen. Now
increasing the window size does not lead to a reasonable scaling of the
transaction fields over the entire area. After all, the scroll bar is
hidden by default. If you do not focus on the scrolling area, you may not
even know that there are more fields. See the screenshots attached.

Regards,
Dmitry

**Comment by luizstacio** [comment]
Close in favor of: #361
