### ISSUE TITLE
faucet error

### ISSUE THREAD

**Issue by betonamujozu** [FuelLabs/fuels-wallet#299]
### What version of Wallet are you using?

fule wallet

### What is happening?

faucet not working

### steps to reproduce

faucet not working

### How it should behave?

Better performance for best testing experience

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

chrome browser

**Comment by luizstacio** [comment]
This error is on our faucet project. We are currently working to improve it. You can keep track of the faucet repo https://github.com/FuelLabs/faucet/.
