### ISSUE TITLE
Download wallet

### ISSUE THREAD

**Issue by VasylPp** [FuelLabs/fuels-wallet#300]
### What version of Wallet are you using?

Fuel Wallet

### What is happening?

The wallet works, the permission is active, the site still downloads the new Zip

### steps to reproduce

Zip downloaded ---- installed --- created a wallet ---- went to the site -- I click connect the wallet --- does not connect (downloads the zip again)

### How it should behave?

Zip downloaded ---- installed --- created a wallet ---- went to the site -- I click connect the wallet --- wallet connected

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Версия 107.0.5304.108 (Официальная сборка), (64 бит)

**Comment by luizstacio** [comment]
Thanks for the issue. Closing in favor of #301
