### ISSUE TITLE
For some reason my friends and I can't get into Discord

### ISSUE THREAD

**Issue by d1man322** [FuelLabs/fuels-wallet#304]
For some reason, I and my friends do not come into Discord, writes Oops, can not accept the invitation, I thought it was just me, but it turned out not, many others have the same. Although most importantly, I was already discord and left my feedback even about the wallet, but then I kicked out and can not go back. My discord nickname: d1maN#1473
![Screenshot_6](https://user-images.githubusercontent.com/38160266/205179181-7fc4352d-ad31-429c-85d4-0f3130b658bd.png)

**Comment by Rubyt0x** [comment]
Hey @d1man322 if you can't access the server anymore, it means that you broke one of the server rules. It means you either shared a wallet address in the `wallet-feedback` channel or that you shared unauthorized content on the server. 
If you think there has been a mistake, I would be happy to revoke the ban.

**Comment by d1man322** [comment]
> Hey @d1man322 if you can't access the server anymore, it means that you broke one of the server rules. It means you either shared a wallet address in the `wallet-feedback` channel or that you shared unauthorized content on the server. If you think there has been a mistake, I would be happy to revoke the ban.

Oh oops, sorry, I did not know that the reviews can not leave the address of the purse), I thought reviews are checked just the address to find errors in what if anything. I would be grateful if you unblock me, I will not make such mistakes again

**Comment by Rubyt0x** [comment]
Alright, in the future, make sure you read the announcements ;) 
You can join the server now.

**Comment by d1man322** [comment]
> Alright, in the future, make sure you read the announcements ;) You can join the server now.

thx my friend :)
