### ISSUE TITLE
tried installing the wallet and it is showing on the extensions but got error in the install

### ISSUE THREAD

**Issue by fastken** [FuelLabs/fuels-wallet#316]
### What version of Wallet are you using?

latest

### What is happening?

getting error as follows:

Context
index.html#/sign-up/welcome
Stack Trace
index.html#/sign-up/welcome:8 (anonymous function)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fuels Wallet</title>
    <script>
      window.global = window;
    </script>
    
    <script type="module" crossorigin src="/assets/index.d2a55d50.js"></script>
    <link rel="modulepreload" crossorigin href="/assets/index.96e45561.js">
    <link rel="modulepreload" crossorigin href="/assets/BaseConnection.4abdf781.js">
    <link rel="modulepreload" crossorigin href="/assets/constants.9bb88d29.js">
    <link rel="modulepreload" crossorigin href="/assets/main.1153f512.js">
    <link rel="stylesheet" href="/assets/main.e95e7c62.css">
  </head>
  <body>
    <div id="root"></div>
    
  </body>
</html>
 
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.

### steps to reproduce

tried installing the wallet extension then clicked on the request for tokens

### How it should behave?

without a failure

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 107.0.5304.121 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
Thanks for the issue, These errors are already on track to be fixed #124.

**Comment by fastken** [comment]
Thanks for letting me know, where will I find out when this is fixed so I can try again?

kind regards

Ken
________________________________
