### ISSUE TITLE
Errors when adding an extension to Google Chrome

### ISSUE THREAD

**Issue by VanDan68** [FuelLabs/fuels-wallet#318]
### What version of Wallet are you using?

0.0.1

### What is happening?

When adding the extension to the browser, several errors occur, as a result, it is impossible to connect the wallet (error 'Cannot read properties of undefined (reading 'connect')'). See attached screenshots.
![Screenshot from 2022-12-02 12-55-32](https://user-images.githubusercontent.com/119664592/205268713-d848251b-1e04-41aa-a962-87d4349e62e6.png)

![Screenshot from 2022-12-02 12-57-25](https://user-images.githubusercontent.com/119664592/205268709-eddd8d46-8540-42b7-9b42-4b550a29f4df.png)

Error #1: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.
![Screenshot from 2022-12-02 12-56-43](https://user-images.githubusercontent.com/119664592/205268711-47509ae2-a818-4137-af13-52d506fe5042.png)

Error #2: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.
![Screenshot from 2022-12-02 13-07-29](https://user-images.githubusercontent.com/119664592/205268703-d7b5e675-b80c-41e4-9e63-28a267551b64.png)

### steps to reproduce

Add Extension to Grome Browser for Ubuntu 22.04.1 LTS

### How it should behave?

There should be no errors when adding an extension

### What os are you seeing the problem on?

None

### What browser?

Chrome

### What is your browser version?

Version 108.0.5359.71 (Official Build) (64-bit)

**Comment by VanDan68** [comment]
There are two more errors now:

Error #3: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.
Context
popup.html
![Screenshot from 2022-12-02 13-22-27](https://user-images.githubusercontent.com/119664592/205271757-08919ecc-f67a-4ff5-9045-3f585dedfd58.png)

Error #4: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.
Context
popup.html
![Screenshot from 2022-12-02 13-22-37](https://user-images.githubusercontent.com/119664592/205271755-57ab857a-3d97-4f21-9aa5-0af5b768194a.png)

**Comment by luizstacio** [comment]
Thanks for the issue, These errors are already on track to be fixed #124.

**Comment by VanDan68** [comment]
> Thanks for the issue, These errors are already on track to be fixed #124.

yw. hope you fix it soon

**Comment by luizstacio** [comment]
@VanDan68, I think PR #317 will fix the error you are having.
