### ISSUE TITLE
connection to fuel swap

### ISSUE THREAD

**Issue by nickpap1** [FuelLabs/fuels-wallet#319]
### What version of Wallet are you using?

beta testnet

### What is happening?

why cant i connect the wallet to fuelswap. At the moment its only possible to make an in browser wallet and swap between eth and dai

### steps to reproduce

clicking any functions at the top right hand side of the browser

### How it should behave?

there should be a way to unplug a wallet for another wallet 

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

windows chrome

**Comment by luizstacio** [comment]
The current SwaySwap application is not using the Fuel Wallet extension, so it does not open the approval screen or connection screens. We are going to implement it soon keep track on the swayswap repo: https://github.com/FuelLabs/swayswap
