### ISSUE TITLE
Fuel wallet asset transfer issues

### ISSUE THREAD

**Issue by h805846716** [FuelLabs/fuels-wallet#320]
### What version of Wallet are you using?

Chrome Plugin Wallet  0.0.1

### What is happening?

When I try to transfer assets (beyond the ninth decimal place) in https://fuels-wallet.vercel.app/docs/how-to-use/ "How to use", the "Transfer" button does not respond.

### steps to reproduce

1.Open： https://fuels-wallet.vercel.app/docs/how-to-use/
2：Request connection：Click the Connectd button  （Correct）
3：List user accounts：Click the Get accounts button  （Correct）
4：Signing a message：Click the Sign Message button  （Correct）
5：Transfering assets：Enter: 0.0000000001, or any other number that exceeds nine decimal places.
6：Click the Transfer button （**No response**）

### How it should behave?

If the team hadn't set it up deliberately, he should have been able to perform the transfer operation with any digit entered.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.72

**Comment by luizstacio** [comment]
The default number of decimals on Fuel is 9 decimals. And for now, the input is not validating the amount, causing the issue, I opened an issue where you can track once it is fixed #323.

About the discord link, it should be working fine. Please considering check our website also https://fuel.network to check other forms to contact the team and get you in the discord.

**Comment by h805846716** [comment]
> 

Thank you for your reply sir, Fuel will get better and better!
