### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by renatghoste** [FuelLabs/fuels-wallet#322]
### Motivation

Adding features to the wallet

### Usage example

1. it is necessary to integrate the creation of accounts on the wallet
2. The link to the discord in the wallet does not work

**Comment by luizstacio** [comment]
1. We already have this on our roadmap. [#20](https://github.com/FuelLabs/fuels-wallet/issues/20) [#21](https://github.com/FuelLabs/fuels-wallet/issues/21) [#22](https://github.com/FuelLabs/fuels-wallet/issues/22) you can also check the list of features that are missing but will be developed on the readme: https://github.com/FuelLabs/fuels-wallet#features
2. About the discord link, it should be working fine. Please considering check our website also, https://fuel.network/ to check other forms to contact the team and get you in the discord.
