### ISSUE TITLE
Wallet pasw

### ISSUE THREAD

**Issue by Manar56** [FuelLabs/fuels-wallet#325]
### Motivation

May you add '' Remember my password for the next .... minutes '' feautere. may you add '' Remember my password for the next .... minutes '' feautere. So we could skip to enter password for anytime you specify

### Usage example

''Remember my password ''

### Possible implementations

Adding '' Remember my password for the next .... minutes '' feautere. So we could skip to enter password for anytime you specify.
The extension will now let our remember our password

**Comment by luizstacio** [comment]
We have mapped to change it to a single unlock when you open the Wallet. You can keep track of this here: #244
