### ISSUE TITLE
Confirmation windows width ("approve" and "transaction" windows)

### ISSUE THREAD

**Issue by KipariS** [FuelLabs/fuels-wallet#326]
### Motivation

I'v exp. in Ui/Ux dev, so will be glad to help you if needed ;)

### Usage example

All of this "confirmation", "approve" and "transaction" windows are so wide on full screen. 

### Possible implementations

Just make it much narrow, like 300-400px width and centered.

**Comment by luizstacio** [comment]
Can you explain better what you mean? I think could be related to this issue: #201
