### ISSUE TITLE
Fuel address management with SwaySwap (disconnect, select)

### ISSUE THREAD

**Issue by CryptoWiGo** [FuelLabs/fuels-wallet#327]
### What version of Wallet are you using?

v0.0.1

### What is happening?

We can't select the wallet to be used on SwaySwap app. Is there anyway to deconnect the current Fuel address within SwaySwap so we can reconnect with another Fuel address or add an application link to SwaySwap within the Fuel wallet so we can be connected directly with the default wallet address?
Thanks

### steps to reproduce

see above

### How it should behave?

see above

### What os are you seeing the problem on?

None

### What browser?

Chrome

**Comment by luizstacio** [comment]
The current SwaySwap application is not using the Fuel Wallet extension, so it does not open the approval screen or connection screens. We are going to implement it soon keep track on the SwaySwap repo: https://github.com/FuelLabs/swayswap
