### ISSUE TITLE
Doesn't work Transfering assets

### ISSUE THREAD

**Issue by aleko0o** [FuelLabs/fuels-wallet#329]
### What version of Wallet are you using?

testnet

### What is happening?

The transfering assets section always gives an error. The wallet is connected and previous transactions were completed without any problems. My wallet address is fuel1kcw5ev986qrrt5qvntn3rhk0zz933g40az4y07krl7z3j7qrj7sqdhdmru

### steps to reproduce

The transfering assets section always gives an error. The wallet is connected and previous transactions were completed without any problems. My wallet address is fuel1kcw5ev986qrrt5qvntn3rhk0zz933g40az4y07krl7z3j7qrj7sqdhdmru

### How it should behave?

The transfering assets section always gives an error. The wallet is connected and previous transactions were completed without any problems. My wallet address is fuel1kcw5ev986qrrt5qvntn3rhk0zz933g40az4y07krl7z3j7qrj7sqdhdmru

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.71 (Resmi Derleme) (64 bit) Sürümü

**Comment by luizstacio** [comment]
Can you attach some screenshots or steps to help us emulate this issue?

**Comment by aleko0o** [comment]
Like this. I tried many times but the result is the same. I can't do the
send function.

7 Ara 2022 Çar 00:32 tarihinde Luiz Estácio | stacio.eth <
***@***.***> şunu yazdı:
