### ISSUE TITLE
Can't connect Wallet in the website : https://fuels-wallet.vercel.app/

### ISSUE THREAD

**Issue by tanthanhbk95** [FuelLabs/fuels-wallet#330]
### What version of Wallet are you using?

I can't see 

### What is happening?

I don't know how to connect

### steps to reproduce

Give us more guideline

### How it should behave?

![image](https://user-images.githubusercontent.com/117377274/205476684-f95f8c5f-772c-4e65-8fae-f3e79a0784eb.png)

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

The latest

**Comment by luizstacio** [comment]
To connect the wallet, you need to access it through a DApp. You can use the page provided on our docs to test: https://fuels-wallet.vercel.app/docs/how-to-use/

About the alert window, the send transaction is not implemented yet you can track it here: #324
