### ISSUE TITLE
Wallet Connection problem 

### ISSUE THREAD

**Issue by bossanjo** [FuelLabs/fuels-wallet#331]
### What version of Wallet are you using?

Zip file you provided

### What is happening?

" Cannot read properties of undefined (reading 'connect') " i get this error sometimes when refreshed the https://fuels-wallet.vercel.app/docs/how-to-use/ page and trying to connect my wallet. 

### steps to reproduce

Open https://fuels-wallet.vercel.app/docs/how-to-use/ , click Connect 

### How it should behave?

Could Connect and Disconnect without changing google chrome extension allowances of Fuel wallet, or refresh page. 

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

Latest chrome

**Comment by luizstacio** [comment]
Do you have the wallet extension install?

**Comment by bossanjo** [comment]
Yes of course, it sometimes gives error when trying to connect, and
sometimes not.

5 Ara 2022 Pzt 22:07 tarihinde Luiz Estácio | stacio.eth <
***@***.***> şunu yazdı:

**Comment by luizstacio** [comment]
Thanks for the reply. This will be fixed by issue #308.

**Comment by bossanjo** [comment]
Awesome, thanks!

6 Ara 2022 Sal 00:34 tarihinde Luiz Estácio | stacio.eth <
***@***.***> şunu yazdı:
