### ISSUE TITLE
The dapp is also showing the same link as install option 

### ISSUE THREAD

**Issue by pppkartik** [FuelLabs/fuels-wallet#337]
### What version of Wallet are you using?

Don't know

### What is happening?

The dapp is not showing

### steps to reproduce

It should connect wi my wallet for test a transanction

### How it should behave?

It's completely not working 

### What os are you seeing the problem on?

Windows Desktop

### What browser?

None

### What is your browser version?

Windows 11

**Comment by luizstacio** [comment]
@pppkartik  Can you point to what DApp you are testing?

**Comment by pppkartik** [comment]
Fuel wallet dapp sir
