### ISSUE TITLE
We want make an AMA with you

### ISSUE THREAD

**Issue by EmirAltun** [FuelLabs/fuels-wallet#353]
### Motivation

Hello. My name is Emir. I am moderator and Editor at Huginn Academy. We are one of the biggest crypto community in Turkey.We are doing testnets,Technical/Fundamental analysis,educational videos and sharing them. Also we have Youtube,Instagram and other social media platforms.
 
We want to prepare an AMA event with you. We are a community made up of many well-known people(I'll leave the links at the bottom.). We can make an event professionally and with high quality. We would be grateful that making an event to introduce you. If you are interested, I will look forward to your response. 
 
 
 
Best regards !
 
Huginn Academy 

### Usage example

Huginn.Academy (@HuginnAcademy) / Twitter
 
Huginn Academy - YouTube
 
Huginn #Testnet (@HuginnTestnet) / Twitter
 
Huginn Staking (@HuginnStake) / Twitter
 
Rua (@Rhuax) / Twitter
 
discord.gg/huginn

### Possible implementations

Please contact with me on mail.
emir@huginn.academy

**Comment by Rubyt0x** [comment]
Hey @EmirAltun,
Thanks for reaching out. Feel free to message me on Telegram so we can talk about it https://t.me/Rubyt0

**Comment by matt-user** [comment]
closing this as it seems to be resolved
