### ISSUE TITLE
we need always sıgn message ? 

### ISSUE THREAD

**Issue by onderfehmi** [FuelLabs/fuels-wallet#356]
### Motivation

when confirming the transaction
always asking for my signature
i think this is a waste of time
is there any way to change this?

**Comment by luizstacio** [comment]
Can you explain better if the signature is the issue or the password? Asking for password every time will be changed but asking for signatures is something required to imagine an app that can do signatures by your self. It would enable the DApp to move all your funds without you knowing.

**Comment by onderfehmi** [comment]
signature and approval and the latest checks are indispensable for this job. I just think that entering the password in every transaction is a waste of time, other than that, everything is great, but I had a discord problem and now I can't enter the discord, can you help?

iPhone’umdan gönderildi

Luiz Estácio | stacio.eth ***@***.***> şunları yazdı (12 Ara 2022 11:15):

﻿

Can you explain better if the signature is the issue or the password? Asking for password every time will be changed but asking for signatures is something required to imagine an app that can do signatures by your self. It would enable the DApp to move all your funds without you knowing.

**Comment by luizstacio** [comment]
Thanks for the issue. We are working on refactoring this flow to a single unlock when you open the Wallet. You can keep track of this here: #244
