### ISSUE TITLE
I first added 19 days to the liquidity pool and after the tap request I was able to exchange these dai for eth without taking them out of the pool

### ISSUE THREAD

**Issue by ratimirs** [FuelLabs/fuels-wallet#357]
see the activity of my wallet fuel1rgm3uz2aejycl985g2fzgr0fcsncv6zkptqvtx4ctk0uz4nlzlzq9lxskq
I first added 19 days to the liquidity pool and after the tap request I was able to exchange these dai for eth without taking them out of the pool!!! It was not possible to do this again

**Comment by luizstacio** [comment]
I didn't understand the 19 days, as the liquidity pool on SwaySwap requests you to deposit ETHs and DAIs and return a new liquidity token.

**Comment by luizstacio** [comment]
Closing by inactivity.
