### ISSUE TITLE
Make the wallet available on chrome extension

### ISSUE THREAD

**Issue by HermesXchange** [FuelLabs/fuels-wallet#367]
### Motivation

majority of user will be scared of downloading random file into there pc and installing the extension manually due to a lot of scams and hacking occurring lately.

### Usage example

I have a friend I introduced fuel beta testing to he said this is scam immediately he discovered the process of installing the extension  as result of his past experience. I need to take my time and explain everything to him.

### Possible implementations

Make the wallet extension available on goggle chrome, Thank You

**Comment by luizstacio** [comment]
@HermesXchange, thanks for the issue. As the current version is beta and with some main features missing. Because of this, for now the installation is just via zip file, but the release on the web store is soon. Keep track here #125.
