### ISSUE TITLE
Storybook for Account and Home Pages has a loading bug

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-wallet#369]
### What version of Wallet are you using?

0.0.2

### What is happening?

If you open the Account or Home pages initially in the storybook or refresh while on the pages they get stuck loading.

Issue #144 might be related to this bug.

### steps to reproduce

Open the Account or Home pages initially or refresh while on the pages in the storybook.

### How it should behave?

They pages should be loading for a little bit while they fetch from the account service and then display the account information.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

None

**Comment by luizstacio** [comment]
Related to #305
