### ISSUE TITLE
Chapta in faucet site does not work through Brave browser

### ISSUE THREAD

**Issue by Mazuikka** [FuelLabs/fuels-wallet#379]
### What version of Wallet are you using?

0.0.1

### What is happening?

Chapta won't open/doesn't show mission in Faucet website. 

![Näyttökuva 2022-12-20 101943](https://user-images.githubusercontent.com/118826257/208617756-b12f18ac-553c-4f76-86d1-fb0fce690782.png)

### steps to reproduce

I load the wallet into the Brave browser. Once the address is created, I press the Faucet button on the wallet and get to the faucet page. Chapta doesn't open on the faucet page and I can't request funds for the test network.

### How it should behave?

I was waiting for a button to run Chapta and order test ethers. The button did not appear and the task did not open.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Other

### What is your browser version?

1.46.144

**Comment by luizstacio** [comment]
Thanks for the issue, this error is on our faucet project. We are currently working to improve it. You can keep track of the faucet repo https://github.com/FuelLabs/faucet/.
