### ISSUE TITLE
Reload Transaction Request Screen makes the app break

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#392]
### What version of Wallet are you using?

0.0.1

### What is happening?

in DAPP screen to approve a transaction screen , if you press cmd+r (reload), multiple problems happen:

- empty transaction screen
- allowed to navigate through the app freely in an approval-only screen
- when click in menu, app gets smaller

https://user-images.githubusercontent.com/8636507/209029506-838a2e3c-66c2-48e6-b266-65ad183ad2e3.mov

**Comment by luizstacio** [comment]
I think we should save the tx requested in memory to avoid this issue, as blocking the reload is not possible.

**Comment by LuizAsFight** [comment]
@luizstacio solution is to close popup if reload... it's safer.. same way metamask does
