### ISSUE TITLE
connectıng problem

### ISSUE THREAD

**Issue by onderfehmi** [FuelLabs/fuels-wallet#403]
### What version of Wallet are you using?

FuelLabs/fuels-wallet google extensıon

### What is happening?

https://imgur.com/3nZAyaQ   ı have connectıon problem I have been using it for 1 month without any problems.
but today i faced connection problem for the first time
and i can't solve the problem
Also I don't know why
they kicked me from discord onderfehmi#6267
you can see I did not do any illegal activities
I want to join discord again
onderfehmi@hotmail.com my e-mail address can you send me a link
And how do we solve the problem I mentioned above?

### steps to reproduce

![image](https://user-images.githubusercontent.com/85879763/209427667-3c498911-0317-4abb-adf1-0a2a80deaf62.png)

### How it should behave?

I'm waiting for the problem to be resolved
Also, if I can enter discord, I will make more useful quick reports.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.125 ((64 bit)

**Comment by onderfehmi** [comment]
![image](https://user-images.githubusercontent.com/85879763/209919465-ed7a7273-f9ea-4f66-924a-5942015a2779.png)
ı dont know how but the problem ıs solved manually

**Comment by luizstacio** [comment]
@onderfehmi after installing the extension you need to restart the page for the sdk fuel be injected.
