### ISSUE TITLE
The wallet has a password error. But the password I entered is correct.

### ISSUE THREAD

**Issue by shuige8888** [FuelLabs/fuels-wallet#404]
### What version of Wallet are you using?

The latest version of the test version. No version number can be seen

### What is happening?

Wallet address：fuel1ngyl6529ynw0865af0dwc2avrv8ds455xr5gxy3qt3x5qjgmscjsf7p5vd
During the BATA2 test, if you enter the correct password, you will be prompted that the password is incorrect. You can click OK later!

### steps to reproduce

During the BATA2 test, if you enter the correct password, you will be prompted that the password is incorrect. You can click OK later!

### How it should behave?

The error should not be displayed when the password is correct

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.125

**Comment by luizstacio** [comment]
@shuige8888, Thanks for the report, update the Wallet to the Latest version v0.7.2, the version is shown on the sidebar bottom and should be 0.7.2 or bigger. If the error still exists please let me know.
