### ISSUE TITLE
doesn't need to sign anything

### ISSUE THREAD

**Issue by Hejartech** [FuelLabs/fuels-wallet#405]
### What version of Wallet are you using?

0.0.1

### What is happening?

When I open the wallet even after weeks, it doesn't to enter any password and it's open.

Also when I want to swap here: https://fuellabs.github.io/swayswap/swap?from=ETH&to=DAI
I don't need to sign anything to do the swap. Why is that?? Is it a bug or a feature??

### steps to reproduce

-

### How it should behave?

It should need sign a message to complete the swap

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

1.46.144

**Comment by luizstacio** [comment]
The current version doesn't unlock itself, as the data is ready only. All the signature part requires the user to enter the password. We are working on changing this flow to unlock after a couple of minutes and only request the password once.

About SwaySwap, the application is not connected to the wallet. SwaySwap uses a disposable wallet and saves it on the website storage. This is why it didn't request signatures to the wallet.
