### ISSUE TITLE
Can't making swap on SwaySwap.

### ISSUE THREAD

**Issue by 0xSaubhagya** [FuelLabs/fuels-wallet#406]
### What version of Wallet are you using?

Fuel Wallet 0.0.1

### What is happening?

![sway](https://user-images.githubusercontent.com/119060982/210161991-bd0bbd11-9c07-4a60-9295-eefa9a3ce9ab.jpg)
 
As you can see in the screenshot that its saying "Insufficient ETH for gas", but i have 6.1 ETH on my Fuel wallet 
 ( fuel1gpmjwc738x5yxhghspl3ndxqw33y55lud4xyqsqux0hpcz0p3y3q90h4nt )
Here is the screenshot of my Fuel wallet.
![fwallet](https://user-images.githubusercontent.com/119060982/210162046-3659fa2a-4de4-404a-b196-6888fdf809ac.jpg)

### steps to reproduce

Go to the SwaySwap : https://fuellabs.github.io/swayswap/swap?from=DAI&to=ETH  , the you will find two features on SwaySwap - SWAP & POOL. Click on the swap, swap ETH for DAI and you will see this error.

### How it should behave?

It should normally complete the swap transaction, but its showing Insuficient gas.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 108.0.5359.125 (Official Build) (32-bit)

**Comment by h805846716** [comment]
Sir, Sway is currently a demo program that automatically generates burning addresses. So Sway cannot interact with the Fuel extension wallet. You can request test funding for Sway at the bottom left of the page.
![image](https://user-images.githubusercontent.com/85295625/211133422-28ddd05d-9d20-43d3-bec6-284b2ca0462a.png)

**Comment by matt-user** [comment]
As @h805846716 mentioned you cannot currently use the fuel wallet extension with sway swap.  Use the burner wallet that swayswap generates if you want to interact with the demo.
