### ISSUE TITLE
fuels-wallet.vercel.app website disconnected Does not work properly

### ISSUE THREAD

**Issue by shkudun** [FuelLabs/fuels-wallet#416]
### What version of Wallet are you using?

0.0.1

### What is happening?

![image](https://user-images.githubusercontent.com/85562094/210573393-7020527c-869a-470e-82fb-0816efacf0f8.png)
At this point, the connected button works fine.
and the button is disabled Doesn't work properly

### steps to reproduce

![image](https://user-images.githubusercontent.com/85562094/210573735-04ac1e86-ea70-4cc3-a329-7cec8f0bc08b.png)
![image](https://user-images.githubusercontent.com/85562094/210573796-12d21b11-ef23-4195-ba9e-0a26b9f63f44.png)

### How it should behave?

As soon as I clicked on the disconnect button, the connect button should light up, but this does not happen

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 108.0.5359.99 (Official build), (64 bit)

**Comment by luizstacio** [comment]
Hi, we have fixed this issue. It was [an issue with docs](https://github.com/FuelLabs/fuels-wallet/pull/424/files#diff-140a766dba120fd60b5f7b1413865c25a6884f2b9363e09b451ec456162b74ef) state of the connection.
