### ISSUE TITLE
InsufficientInputAmount error even with balance on the Wallet

### ISSUE THREAD

**Issue by onderfehmi** [FuelLabs/fuels-wallet#420]
### What version of Wallet are you using?

FuelLabs/fuels-wallet google extensıon

### What is happening?

![image](https://user-images.githubusercontent.com/85879763/211073808-ebf4278f-36a6-4d29-84fa-ed703b8c5c00.png)
I have already funds but stıll had thıs problem..

### steps to reproduce

fuel12j4t6pcwpcz38xjh3pyay20xl535nh3fgz2kufj9yza5utwchtjs8fxh5l wallet adress 

InsufficientInputAmount { asset: 0000000000000000000000000000000000000000000000000000000000000000, expected: 302000100, provided: 191258419 }: {"response":{"data":null,"errors":[{"message":"InsufficientInputAmount { asset: 0000000000000000000000000000000000000000000000000000000000000000, expected: 302000100, provided: 191258419 }","locations":[{"line":2,"column":3}],"path":["dryRun"]}],"status":200,"headers":{"map":{"content-type":"application/json"}}},"request":{"query":"mutation dryRun($encodedTransaction: HexString!, $utxoValidation: Boolean) {\n  dryRun(tx: $encodedTransaction, utxoValidation: $utxoValidation) {\n    ...receiptFragment\n  }\n}\n\nfragment receiptFragment on Receipt {\n  data\n  rawPayload\n}","variables":{"encodedTransaction":"0x000000000000000000000000000000000000000005f5e100000000000000000000000000000000040000000000000000000000000000000100000000000000020000000000000001000000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000a0dc914e0ee7551bf651b610bbaf547b2d486cc8c68f7fc28de612513cbffd27000000000000000154aabd070e0e05139a578849d229e6fd2349de2940956e264520bb4e2dd8bae5000000000b665f33000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c78a0266f7e10eb47872f0dc60a984625d01635c2723d61dccb9f555702a41000000000120027e40000000000000000000000000000000000000000000000000000000000000000000000000000000354aabd070e0e05139a578849d229e6fd2349de2940956e264520bb4e2dd8bae5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","utxoValidation":false}}}

### How it should behave?

first time encountering such a problem
maybe instant json may be the problem but I still wanted to share it with you

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.125 ((64 bit)

**Comment by luizstacio** [comment]
@onderfehmi, we were able to reproduce the issue, and it's been fixed on the SDK level. https://github.com/FuelLabs/fuels-ts/pull/736 thanks for reporting.
