### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by onderfehmi** [FuelLabs/fuels-wallet#421]
### What version of Wallet are you using?

tx problems 

### What is happening?

InsufficientInputAmount { asset: 0000000000000000000000000000000000000000000000000000000000000000, expected: 200200100, provided: 199968996 }: {"response":{"data":null,"errors":[{"message":"InsufficientInputAmount { asset: 0000000000000000000000000000000000000000000000000000000000000000, expected: 200200100, provided: 199968996 }","locations":[{"line":2,"column":3}],"path":["dryRun"]}],"status":200,"headers":{"map":{"content-type":"application/json"}}},"request":{"query":"mutation dryRun($encodedTransaction: HexString!, $utxoValidation: Boolean) {\n  dryRun(tx: $encodedTransaction, utxoValidation: $utxoValidation) {\n    ...receiptFragment\n  }\n}\n\nfragment receiptFragment on Receipt {\n  data\n  rawPayload\n}","variables":{"encodedTransaction":"0x000000000000000000000000000000000000000005f5e100000000000000000000000000000000040000000000000000000000000000000100000000000000020000000000000001000000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000a03499e7f496733e9887bf7e578cf0c90415cfe266851b25c24fdf61cdcb228c000000000000000154aabd070e0e05139a578849d229e6fd2349de2940956e264520bb4e2dd8bae5000000000beb48e4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c78a0266f7e10eb47872f0dc60a984625d01635c2723d61dccb9f555702a410000000000beecfa40000000000000000000000000000000000000000000000000000000000000000000000000000000354aabd070e0e05139a578849d229e6fd2349de2940956e264520bb4e2dd8bae5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","utxoValidation":

### steps to reproduce

There is no problem with small investments.
but when I want to make an investment like 0.20 eth, I get an error in these transfers.

### How it should behave?

.

### What os are you seeing the problem on?

None

### What browser?

None

**Comment by luizstacio** [comment]
What is the amount balance you have in your wallet? The error looks like you don't have the amount + gasFee necessary to do the tx.

**Comment by luizstacio** [comment]
Have you tried to faucet some funds before trying the action `transfer`. If you have a balance and the error is showing, please send a comment here so we can re-open the issue.
