### ISSUE TITLE
Add examples to documentation about how to listen to wallet events

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-wallet#422]
### Motivation

It would be useful for new developers to give them examples on how to listen for wallet events.  At the very minimum we should list all of the possible wallet events that can be listened for.

### Usage example

One example could be
```
fuel.on("connect", () => { console.log("connected") });
```
But at the minimum we should list all of the events the wallet sdk will can emit.

**Comment by arboleya** [comment]
I'd suggest having a `WalletEventsEnum` to avoid trivial event name misspellings:

```ts
export enum WalletEventsEnum {
  ACCOUNT_CONNECTED = 'account-connected'
}
```

Perhaps nesting them under a common exported keyword on the `fuels` scope could also be helpful:

```ts
fuel.on(fuel.events.ACCOUNT_CONNECTED, () => { console.log("connected") });
```

Of course, this requires adding full event-handling capabilities to the Wallet.

I've played with [event handling](https://github.com/arboleya/happens) in the past, but I'm sure there are more up-to-date and modern libs to do it.

**Comment by luizstacio** [comment]
> I'd suggest having a `WalletEventsEnum` to avoid trivial event name misspellings:
> 
> ```ts
> export enum WalletEventsEnum {
>   ACCOUNT_CONNECTED = 'account-connected'
> }
> ```
> 
> Perhaps nesting them under a common exported keyword on the `fuels` scope could also be helpful:
> 
> ```ts
> fuel.on(fuel.events.ACCOUNT_CONNECTED, () => { console.log("connected") });
> ```
> 
> Of course, this requires adding full event-handling capabilities to the Wallet.
> 
> I've played with [event handling](https://github.com/arboleya/happens) in the past, but I'm sure there are more up-to-date and modern libs to do it.

The Wallet already had an event system for accounts, connection, and network. If the user adds TypeScript, it already supports autocomplete and check, but it will be great to also export as an enum. Thanks for the add.
