### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LennyIcejd00** [FuelLabs/fuels-wallet#427]
### What version of Wallet are you using?

0.0.1

### What is happening?

Address: fuel1zsn4w9plsn6ghwt3yuyhprj4v3x3nps67dmv49nansrfedhzc7nq4lvwn4
Discord: LennyIcejd00#0106
Error:
not enough resources to fit the target: {"response":{"data":null,"errors":[{"message":"not enough resources to fit the target","locations":[{"line":2,"column":3}],"path":["resourcesToSpend"]}],"status":200,"headers":{"map":{"content-type":"application/json"}}},"request":{"query":"query getResourcesToSpend($owner: Address!, $queryPerAsset: [SpendQueryElementInput!]!, $excludedIds: ExcludeInput) {\n  resourcesToSpend(\n    owner: $owner\n    queryPerAsset: $queryPerAsset\n    excludedIds: $excludedIds\n  ) {\n    ...coinFragment\n    ...messageFragment\n  }\n}\n\nfragment coinFragment on Coin {\n  utxoId\n  owner\n  amount\n  assetId\n  maturity\n  status\n  blockCreated\n}\n\nfragment messageFragment on Message {\n  amount\n  sender\n  recipient\n  data\n  nonce\n  daHeight\n  fuelBlockSpend\n}","variables":{"owner":"0x142757143f84f48bb9712709708e55644d19861af376ca967d9c069cb6e2c7a6","queryPerAsset":[{"assetId":"0x0000000000000000000000000000000000000000000000000000000000000000","amount":"1"}],"excludedIds":{"messages":[],"utxos":[]}}}}

### steps to reproduce

click on "Transfer"

### How it should behave?

without errors

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

94.0.4606.54

**Comment by matt-user** [comment]
Did you faucet funds into your wallet?  If not it won't be able to pay for any transactions

**Comment by luizstacio** [comment]
As matt mentioned, you need to faucet some funds before trying the action `transfer`. The error `not enough resources to fit the target` means you don't have enough balance to pay for transfer + gas. If you have a balance and the error is showing, please send a message here so we can re-open the issue.

**Comment by odharmiecrypto** [comment]
I still have this error with 0.5eth faucet...
