### ISSUE TITLE
Wallet version wrong in extension manager

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-wallet#429]
### What version of Wallet are you using?

0.03

### What is happening?

The extension manager shows that my extension version is 0.0.1 when in fact it is not as I can use functionality only available in later version of the extension (0.0.3)

### steps to reproduce

Check your extension version in the extension manager

### How it should behave?

It should show the correct/updated extension version.  This probably isn't a high priority issue as of right now, but in the future it will be hard to help people debug problems with the wallet if we can't tell what version a user actually has installed.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
@matt-user today, we don't control the version of the Wallet zip, making all the releases under version 0.0.1. Version 0.3.0 si related to the SDK package only.

The control for the version of the Wallet extension will be implemented once we start releasing it to the web store. #125

**Comment by matt-user** [comment]
That makes sense thanks for the clarification
