### ISSUE TITLE
App break when click on menu before loading completes

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#430]
### What version of Wallet are you using?

0.0.3

### What is happening?

When clicking on `Menu` button before loading complete, it breaks

### steps to reproduce

https://user-images.githubusercontent.com/8636507/212939290-095061a0-b6ce-4b64-afe1-c1c6942569ab.mov

### How it should behave?

should just open the menu, or hide if it shouldn't be opened while loading.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

**Comment by luizstacio** [comment]
@LuizAsFight can you upload again the video?

**Comment by LuizAsFight** [comment]
@luizstacio uploaded again, sorry for that I probably clicked submit issue before upload completed
