### ISSUE TITLE
Fuel wallet has some issues 

### ISSUE THREAD

**Issue by Heymma** [FuelLabs/fuels-wallet#431]
### What version of Wallet are you using?

0.0.1

### What is happening?

I tried connecting to this site (https://fuels-wallet.vercel.app/docs/how-to-use/) and it's bringing out the pop up when I click connect but it's not showing anything on the popup page 
And also in the wallet on desktop mode I'm unable to look at my phrase when I click the three horizontal line it shows a blank page 

### steps to reproduce

When I click connect on this site (https://fuels-wallet.vercel.app/docs/how-to-use/) 
And also in the wallet on desktop mode when you click the three horizontal line 
![Screenshot_20230112-081522](https://user-images.githubusercontent.com/74108070/212001794-e57e7d42-865c-4899-b59e-1222278c5b0a.png)

https://user-images.githubusercontent.com/74108070/212001912-abe07ef0-a7c0-4480-8c2d-595733175b66.mp4

https://user-images.githubusercontent.com/74108070/212001998-8375f13d-6157-4722-835e-6e239d9ff16b.mp4

### How it should behave?

For the site it's supposed to just show something on the pop up tab 
And also on the wallet it's supposed to also show what's on the three horizontal line 

### What os are you seeing the problem on?

Android Mobile

### What browser?

Other

### What is your browser version?

107.0.5304.74

**Comment by luizstacio** [comment]
Hi @Heymma, Thanks for the report. Currently, we don't support the kiwi mobile browser. You can track the supported browsers here: https://wallet.fuel.network/docs/browser-support/. Also, If you can debug and fix it, we would appreciate a PR, as other users also reported issues with the mobile browsers for android.
