### ISSUE TITLE
Can't recover Old wallet address

### ISSUE THREAD

**Issue by PookieZero** [FuelLabs/fuels-wallet#433]
### What version of Wallet are you using?

Not specified

### What is happening?

I accidently deleted fuel wallet. I somehow installed it agin. Passphrase are same too but I can't recover/get old wallet address. as you can see in the imazes check the address.
![Screenshot 2023-01-14 13 07 52](https://user-images.githubusercontent.com/113176901/212461160-ccdae83d-86be-472f-ba41-f3cc21f09870.png)
![Screenshot 2023-01-14 13 07 32](https://user-images.githubusercontent.com/113176901/212461164-af00b22b-97dc-40b9-9037-9616922baf76.png)

### steps to reproduce

I cannot reconnect new account to the swap either.

### How it should behave?

I should be able to recover my old wallet.

### What os are you seeing the problem on?

None

### What browser?

Chrome

### What is your browser version?

latest

**Comment by luizstacio** [comment]
The current SwaySwap application is not using the Fuel Wallet extension, so it does not show the same accounts. You can keep track on the SwaySwap repo: https://github.com/FuelLabs/swayswap to see when we integrate both wallets.

SwaySwap uses a disposable wallet and saves the private key on localStorage. You can clean the website data to reset the wallet.
