### ISSUE TITLE
Improve performance of png images

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#436]
### Motivation

We're using some `png` files in the project, and they have space for optimization, improving the loading speed.

I did this example using `tinypng` and it improved a lot the `empty-list.png` file.

We should improve all of our `png` files.

![image](https://user-images.githubusercontent.com/8636507/212720988-55ef9ca1-866c-4fa9-8a7a-e244d6b7290c.png)

**Comment by luizstacio** [comment]
We can also use a javascript pre-processor using vite to do the work during the build process.
