### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by Rodme10** [FuelLabs/fuels-wallet#471]
### What version of Wallet are you using?

0.0.1

### What is happening?

The wallet is not showing the correct balance. Always shows 0.5 Eth balance

### steps to reproduce

![Captura de Tela (1600)](https://user-images.githubusercontent.com/105119989/214166506-daa758b4-3a94-43f9-b89b-e7a6ab04419d.png)

### How it should behave?

The wallet should show the same balance as the swayswap

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

1.47.171

**Comment by luizstacio** [comment]
The current SwaySwap application is not using the Fuel Wallet extension, so it the balances will not be the same also, tx history will be different. We are going to implement it in the future you can track on the SwaySwap repo: https://github.com/FuelLabs/swayswap
