### ISSUE TITLE
Create Asset management tool

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#479]
The nature of the UTXO enables the wallet to list all assets from a given account, but now the Wallet only lists the known assets from a hardcoded list, making it impossible to see other assets.

To improve this, we should create a way for adding custom assets metadata;

Where;
- Users add custom tokens to the wallet, making their UTXOs with unknown assets ids been shown on the Wallet, the metadata required is;
  - Name
  - Symbol
  - Image
  - Asset Id
- DApp developer to request adding assets to the user's Wallet.

Note: Also consider on this feature a fetch to a static json containing tokens metadata.

**Comment by lzhabo** [comment]
looking forward for this implementation! ⚡️
This is sorely missed.
