### ISSUE TITLE
Account Info on Signature Request

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#483]
Improve signature request, adding more information on the **website requesting info** and **signer account.**

- Adding website info component
- Add signer account info

[<img width="360" alt="Dapp Integration #2 - Signature Request" src="https://user-images.githubusercontent.com/3941923/214188893-892320ec-415d-470f-b453-95a6aa191de2.png">
](https://www.figma.com/file/uEckQY4EaQ5rXwyISg6d1g/Fuel-Wallet?node-id=118%3A13044&t=IhItfPWrUeAednFK-4)

**Comment by tomiiide** [comment]
Closing as it was done in #589
