### ISSUE TITLE
Request Transaction Screen

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#484]
Improve signature request, adding more information about the **website requesting info** and **warning disclaimer for the user.**

- Adding website info component
- Add warning disclaimer
- On loading state, the warning and website info should be already on the page. Enabling users to read other info before TX is ready to approve.

Note: This screen is similar to the confirm transaction on send transaction flow and can be reused.

[<img width="360" alt="Dapp Integration #3 - Approve Transaction" src="https://user-images.githubusercontent.com/3941923/214196150-66bac378-81ec-449c-a631-4aad53b42a34.png">
](https://www.notion.so/fuellabs/Request-Transaction-Screen-5b3221d6421a4d15910b307c69691e44#86b78d24f87a4fbbbb14df02a7c3a753)

**Comment by tomiiide** [comment]
Closing as it was done in https://github.com/FuelLabs/fuels-wallet/pull/589
