### ISSUE TITLE
Logout confirmation

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#494]
[FRO-66](https://linear.app/fuel-network/issue/FRO-66/logout-confirmation)

As logout is an action that can lead users to lose the seed phrase, we should add an input forcing the user to type before allowing the logout.

- Add confirmation input: "I have my recovery phrase.”

**Comment by izuchukwu-eric** [comment]
Hi @luizstacio I would love to contribute to this project, and i think this issue is a good place to start. can you assign this to me? also i tried accessing the linear workspace, is this open to contributors?
