### ISSUE TITLE
Create full SignUp flow

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/fuels-wallet#5]
## Figma Reference
https://www.figma.com/file/uEckQY4EaQ5rXwyISg6d1g/Fuel-Wallet?node-id=206%3A9374

## Screens
- [ ] Welcome screen
- [ ] Show mnemonic screen
- [ ] Write mnemonic screen
- [ ] Create password
- [ ] Done

## Blocked by
- #4 
- https://github.com/FuelLabs/fuel-ui/issues/119
- https://github.com/FuelLabs/fuel-ui/issues/120
- https://github.com/FuelLabs/fuels-wallet/issues/19

**Comment by luizstacio** [comment]
This issue should also include tests, I suggest using cypress.
