### ISSUE TITLE
Add error reporting tool, that works offline

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#501]
[FRO-71](https://linear.app/fuel-network/issue/FRO-71/add-error-reporting-tool-that-works-offline)

It's normal for applications to break, but with our compromise to privacy, we should look for solutions to enable offline log collection and create a flow for users to download and submit the logs once an unexpected error happens.

related to: #497

**Comment by tibi77** [comment]
Do we have any off-the-shelf tools? Or do we just MacGyver our way through it? Either way, I m quite interested in how this pans out.
