### ISSUE TITLE
[RFC] Fuel Wallet Connectors

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#506]
# Fuel Wallet Connector

## Objective
Enable connectors that are not extensions to seamlessly integrate with Fuel Wallet's multiple connector standard, thus enhancing application-DApp interoperability.

## Background

As blockchain Wallet evolved, each wallet chose its protocol, combining different integration methods. To solve these problems, we saw many abstractions tooling to make a single interface to integrate with multiple Wallet types.

On Fuel, we start with a Connectors protocol to enable multiple Wallet Providers to integrate directly on the Fuel Wallet SDK,  removing the need for other abstractions when developing Applications.

The current implementation of the Fuel Wallet Connectors only works with browser extensions. This proposal aims to change that, opening up more customization possibilities. 

## Problem Statement

_How can we improve the methods through which applications interact with different types of connectors, including those that are not browser extensions?_

## Definitions

- Fuel Wallet SDK: Manager component used for developers to integrate with the Fuel Wallet Connectors.
- Fuel Wallet Connector: Component provided by a Wallet Application that implements the logic for the communication between the Fuel Wallet SDK and the Wallet Application.

## Goals

- Implement a set of methods and events that will standardize interactions between applications and connectors.
- Enable application information and installation instructions through connector metadata.
- Allow Fuel Wallet SDK to detect installed Wallets automatically.
- Remove abstractions for the communication between SDK and Fuel Wallet Connectors.

#### Methods
- The system will expose methods like ping, version, isConnected, etc. to enable standardized interaction.

#### Events
- Events like `accounts`, `currentAccount`, `connection`, etc., will be emitted to communicate changes.

#### Connector Metadata
- A metadata field for connectors will store name, image, and installation instructions.

#### Fuel Wallet SDK
- The SDK connects the connectors, to invoke the exposed methods and listen to various events.

#### Method list

| Method | Description | Params | Return |
| --- | --- | --- | --- |
| ping | It should return true if the connector is loaded in less than one second. |  | boolean |
| version | The current version and the network that this connector supports. |  | Application and network version |
| isConnected | The status of the current connection from the origin to the connector. |  | connection status |
| accounts | Accounts available to the authorized to the current connection. |  | Account address list |
| connect | Start the authorization flow for the current connection. |  | connection status |
| disconnect | Removes the authorization of the current connection. |  | connection status |
| signMessage | Start signMessage flow for the current connection. | address and message | message signature |
| sendTransaction | Start to send transaction flow for the current connection. | address, transaction, and network | transaction ID |
| currentAccount | Return the default account if the account is authorized to the connection. |  | address |
| addAssets | Add assets metadata to the current connection. | Assets metadata | success or failure |
| assets | Return assets metadata available to all accounts, even the ones out of the connection. | Assets metadata | asset list |
| addNetwork | Start to add network flow for the current connection. | Network | success or failure |
| selectNetwork | Request the user to change the network inside the wallet. | Network | success or failure |
| networks | Return network list available to all the accounts from the connector. |  | Network list |
| addABI | Add ABI information. This is a purely metadata endpoint and does not require an authorized connection. | contract id and ABI | boolean |
| getABI | Return ABI information. | contract id | FuelABI |
| hasABI | Return true if an ABI is available. | contract id | success if ABI returns |

#### Event list

| Event | Description | Value |
| --- | --- | --- |
| accounts | Emitted every time the accounts available to this connection change | Addresses |
| currentAccount | Emitted every time the current account on the connector is changed if the account is not available to the current it should be triggered with a null value | Address or null if no defined |
| connection | Emitted every time the connection status changes | Connection status |
| network | Emitted every time the network selected on the connector is updated | Network url and chainId |
| assets | Emitted every time the asset's metadata of the connector is changed | Update asset list |

#### Connector metadata

A new field that will be part of the new connector structure is a metadata property that will be used to enable the application to have information and instructions on how to install the connector application.

```tsx
class FuelWalletConnector extends FuelConnector {
   metadata = {
	  name: 'Fuel Wallet',
	  image: '/connectors/fuel-wallet.svg',
	  install: {
		   action: 'Install',
		   description: 'To connect your Fuel Wallet, install the browser extension.',
		   link: 'https://chrome.google.com/webstore/detail/fuel-wallet/dldjpboieedgcmpkchcjcbijingjcgok',
	  }
	}
}
```

#### Method list

| Method | Description | Params | Return |
| --- | --- | --- | --- |
| connectors | List all connectors available for the instance | | A list of Connectors |
| getConnector | Return a single connector | connector name | Connector instance |
| hasConnector | Return true if the SDK has a connector available | | boolean |
| selectConnector | Change the connector, return true if the connector is available and connected | connector name | Connector instance |
| currentConnector | Return the current connector selected |  | Connector instance |
| getWallet | Return a instance of Fuel Wallet Locked | address and provider instance (optional) | Wallet instance |
| clean | Cleans the data saved on the storage |
| unsubscribe | Remove all open listeners |
| destroy | Remove all open listeners and data stored |

#### Event list

| Event | Description | Value |
| --- | --- | --- |
| connectors | Emitted every time the accounts available to this connection change | Addresses |
| currentConnector | Emitted every time the current account on the connector is changed if the account is not available to the current it should be triggered with a null value | Address or null if no defined |

## Fuel Wallet SDK

With this new change, extensions will not be required to inject objects into the application window. With this new change, the application will be required to install the `@fuel-wallet/sdk` to interact with the application.

```tsx
import { Fuel } from '@fuel-wallet/sdk';
import { FuelWalletConnector } from '@fuel-wallet/sdk';
import { ThirdyPartyConnector } from '@thirdy-party/connector';

// Fuel SDK instance
const fuel = new Fuel({
  // FuelWalletConnector is injected as a default connector
  connectors: [
     new ThirdyPartyConnector(),
  ]
});

// Wait for the connection response
await fuel.connect();

// Event based way
fuel.on('connection', (isConnected) => {
  console.log(isConnected);
});
```

Or as an **automatic injection,** this is made in this way to enable user Wallets that are not installed by the application to be visible on the Connector List.

```tsx
import { Fuel, EventConnector } from '@fuel-wallet/sdk';
import { FuelWalletConnector } from '@fuel-wallet/sdk';
import { ThirdyPartyConnector } from '@thirdy-party/connector';

// Fuel SDK instance
const fuel = new Fuel({
  connectors: [
    new FuelWalletConnector()
  ]
});

// Manual dispatch of the event on the window
window.dispatchEvent(new CustomEvent('FuelConnector', {
  detail: new ThirdyPartyConnector()
}));

// Dispatch using utility EventConnector
window.dispatchEvent(
  new EventConnector(new ThirdyPartyConnector())
);

// Promise way
await fuel.connect();

// Event based way
fuel.on('connection', (isConnected) => {
  console.log(isConnected);
});
```

## Fuel Wallet Connector

The Connector implements an interface compatible with the FuelWalletConnector. Once the connector is connected to the Fuel Wallet SDK instance, which is the main entry point for the application, the FuelConnect controller will target the instance of the Connector and call the methods directly.

This opens better integration possibilities by enabling more customization for Connectors to use WebSockets, events, etc.

Below is a sequence diagram explaining the information flow for a Connection Request (method: 'connect'):
```mermaid
sequenceDiagram
    title Fuel Connect Manager

    participant A as Dapp
    participant B as Fuel Connect
    participant C as Wallet XW Connector (XW)
    participant D as Wallet Application

    A->>B: List connectors
    B-->>A: Receive connectors
    note over A,B: Select connector
    A->>B: Select Connector (XW)
    note over B,D: Check if Wallet application is available
    B->>C:Call ping on (XW) connector
    C->>D:Ping application
    D-->>C:Respond ping
    C-->>B:Receive ping response from (XW)
    B->>B:Save selected Connector (XW)
    B-->>A:Receive success or failure
    note over A,D: Authorize connection (on selected connector)
    A->>B:Ask for connection
    B->>C:Call connect on (XW) connector
    C->>D:Call connect
    D-->>C:Respond with connection status
    C-->>B:Receive connection status from (XW)
    B-->>A:Receive connection status
```

### Fuel Connect Manager Flows
The Fuel Connect Manager oversees the interactions between a decentralized application (DApp), the Fuel Connect layer, and the wallet's connectors. The sequence diagram delineates the flow of events and method calls that occur during the various stages of a connector's lifecycle, from listing to connection establishment.

#### 1. List Connectors
* **Actors**: DApp (A), Fuel Connect (B)
* **Flow**:
  1. The DApp queries Fuel Connect to list available connectors.
  2. Fuel Connect returns a list of available connectors to the DApp.

#### 2. Select Connector
* **Actors**: DApp (A), Fuel Connect (B), Wallet XW Connector (C), Wallet Application (D)
* **Flow**:
  1. The DApp selects a connector, in this case, Wallet XW Connector (XW).
  2. Fuel Connect initiates a `ping` call to verify if the Wallet Application for the selected connector is available.
  3. The `ping` is forwarded from the Wallet XW Connector to the Wallet Application.
  4. The Wallet Application responds to the `ping`.
  5. The Wallet XW Connector confirms the availability back to Fuel Connect.
  6. Fuel Connect saves the selected connector and notifies the DApp of the success or failure of the operation.

#### 3. Authorize Connection
* **Actors**: DApp (A), Fuel Connect (B), Wallet XW Connector (C), Wallet Application (D)
* **Flow**:
  1. The DApp requests to establish a connection using the selected connector.
  2. Fuel Connect calls the `connect` method on the Wallet XW Connector.
  3. The Wallet XW Connector initiates the connection process with the Wallet Application.
  4. The Wallet Application returns the connection status.
  5. The Wallet XW Connector communicates the connection status back to Fuel Connect.
  6. Fuel Connect relays the connection status back to the DApp.

Each of these flows opens up opportunities for customization, such as utilizing WebSockets for more real-time interactions or leveraging events for enhanced UX features.

Understanding these flows provides foundational knowledge to implement, debug, and extend the capabilities of the Fuel Connect Manager within the ecosystem.

## Break changes
* Removal of `window.fuel` injected object on the window.
* `addConector` will now require an Instance of a Fuel Wallet Connector, or it will be removed.

## Risks and Mitigations
* Existing connectors will be required to update to this new standard. This will require coordination and may have backward compatibility issues.
* Existing application will be required to update to `@fuel-wallet/sdk` to move from `window.fuel`.
* Mitigation: A phased rollout and thorough documentation can alleviate these challenges.

## Draft Implementation
[https://github.com/FuelLabs/fuels-wallet/tree/ls/feat/sdk2/packages/sdk2/src](https://github.com/FuelLabs/fuels-wallet/tree/ls/feat/sdk2/packages/sdk2/src)

**Comment by LuizAsFight** [comment]
the DAPP can be using one network (local devnet), but the Wallet can be connected to other network (beta-4)
this raise some issues:
- dapp can't trust on wallet provider + signer instance because they can be on a different network
- dapp show one information, wallet shows other (any data, balance, transactions, etc..)

to fix this issue, when we detect the network of the wallet is different from the one DAPP supports, we can
**ask the extension to change the network**

for this we can add the method:
Method | Description | Params | Return
-- | -- | -- | --
switchNetwork | Change current connection to use the inputted network | Network | success or failure


-------------------
ps: this behavior already exists on connectKit integration and it's pretty useful.
on this case my metamask was connected to foundry(local), but the bridge supports sepolia
![image](https://github.com/FuelLabs/fuels-wallet/assets/8636507/b7f4b4a4-e8f6-457b-b144-39a3b8c6be10)

**Comment by LuizAsFight** [comment]
instead of injecting defaults connectors by *default* 😅 we can expose a method to prepare the default connectors


before
```
const fuel = new Fuel({
  // FuelWalletConnector is injected as a default connector
  connectors: [
     new ThirdyPartyConnector(),
  ]
});
```

after
```
const defaultConnectors = prepareDefaultConnectors({ chain });
const fuel = new Fuel({
  connectors: [
     ...defaultConnectors,
     new ThirdyPartyConnector(),
  ]
});
```

**Comment by LuizAsFight** [comment]
the `Fuel` sdk object can also receive a chain, so we know what chain the DAPP supports and can act based on that

```
const fuel = new Fuel({
  chains,
  connectors: [
     new ThirdyPartyConnector(),
  ]
});
```

**Comment by luizstacio** [comment]
> instead of injecting connectors by default we can expose a method to prepare the default connectors
> 
> this allows the user to have more control and use wathever connectors he wants, without us enforcing default ones
> 
> before
> 
> ```
> const fuel = new Fuel({
>   // FuelWalletConnector is injected as a default connector
>   connectors: [
>      new ThirdyPartyConnector(),
>   ]
> });
> ```
> 
> after
> 
> ```
> const defaultConnectors = prepareDefaultConnectors({ chain });
> const fuel = new Fuel({
>   connectors: [
>      ...defaultConnectors,
>      new ThirdyPartyConnector(),
>   ]
> });
> ```

Why having a method would be better? I think it adds more steps to implement.
In most cases, users will not need to provide any connectors...

**Comment by luizstacio** [comment]
> the `Fuel` sdk object can also receive a chain, so we know what chain(local, beta-4, etc..) the DAPP supports and can act based on that
> 
> ```
> const fuel = new Fuel({
>   chains,
>   connectors: [
>      new ThirdyPartyConnector(),
>   ]
> });
> ```

The idea of having a chains prop makes sense. Let's add this to the specs, also the switchNetwork.

**Comment by LuizAsFight** [comment]
we can enable a input prop `options` for WalletConnector when creating it, which enables any custom use case the wallet itself wants to implement.

```
const fuel = new Fuel({
  chains,
  connectors: [
     new ThirdyPartyConnector({
       layoutMode: 'compact',
     }),
  ]
});
```


examples:
```
layoutMode: 'compact'
appName: app.name,
headlessMode: false,
metadata: app,
name: 'Custom Walllet',
keepConnection
```

**Comment by LuizAsFight** [comment]
> Why having a method would be better? I think it adds more steps to implement. In most cases, users will not need to provide any connectors...


would allow:
- the user to have more control and use wathever connectors he wants, without us enforcing default ones
- with the `defaultConnectors` in hands, user can customize and pass specific props for connectors (`options` from prev comment`
