### ISSUE TITLE
Move from console.debug to console.log on documentation examples

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#547]
[FRO-74](https://linear.app/fuel-network/issue/FRO-74/move-from-consoledebug-to-consolelog-on-documentation-examples)

Recently we have moved from `console.log` to `console.debug` on the docs examples, but this causes confusion as the user needs to change the log level in order to see the logs.

We should move back all console.debug on the docs examples to console.log.

**Comment by SakshiShah29** [comment]
I would like to work on this issue if it is still open.
