### ISSUE TITLE
Show password strength inline 

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#550]
[FRO-75](https://linear.app/fuel-network/issue/FRO-75/show-password-strength-inline)

### Motivation

The password pages now have a security popover showing our rules and security of password

UX problems:
- when popover is open, other fields are hidden
- if you wanna click in the next field, you need to click outside of the popover.
  - if you click in the popover, you need to click again to access the field
- we avoid showing error message feedback, to don't show duplicate feedback + avoid screen dancing
- "New Password" provides feedback in Popover style, while other fields provide error feedback below the field, we should keep consistency

https://user-images.githubusercontent.com/8636507/217633194-4a8b2127-a7e0-4727-b902-1c0b52667f84.mov

------------------------------------------------------

we can improve UX creating a version for this screens `CreatePassword` and `ChangePassword`
- security feedback is provided inside the layout, together with other elements
- change layout to don't take much space
  - make it smaller and more concise, maybe only show missing rules

**Comment by tibi77** [comment]
Can we have the current password check in another page and just after that has been validated we get to the change password screen; but this will require us to change the ChangePasswordFormValues struct as well.
I can not really see, from an ux standpoint how we can have that password strength indicator in there together with the 3 fields and the above disclaimer.
We can presumably show that disclaimer only when they have entered a good enough password...
unsusre how to proceed in here 

cc @LuizAsFight @luizstacio

**Comment by LuizAsFight** [comment]
@tibi77 the idea is to remove the strength popup, and incorporate it inside the layout. needs to be concise and small.

but we don't have mockups for this yet
