### ISSUE TITLE
Bad/useless feedback when user tries to send tx without high enough gas limit

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-wallet#554]
[FRO-76](https://linear.app/fuel-network/issue/FRO-76/baduseless-feedback-when-user-tries-to-send-tx-without-high-enough-gas)

### What version of Wallet are you using?

0.5.1

### What is happening?

I get bad/useless feedback when trying to send a tx without a high enough gas limit.  This makes debugging contract calls harder then it should be.

<img width="1426" alt="Screen Shot 2023-02-08 at 10 44 49 AM" src="https://user-images.githubusercontent.com/54373384/217871577-92749750-d18d-4aa5-b636-dd4699f5b055.png">

### steps to reproduce

Send a transaction with a low gas limit

### How it should behave?

It should provide useful feedback such as "Transaction gas limit is too low.  Try raising the gas limit"

### What os are you seeing the problem on?

None

### What browser?

None

**Comment by luizstacio** [comment]
I this can be covered here: #183
