### ISSUE TITLE
Add copy button to toast with error

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#557]
### Motivation

Sometimes the error is too big to be readable inside a toast. We should add a copy button

### Usage example

![image](https://user-images.githubusercontent.com/8636507/217952389-e86a0f25-bbf1-4cc7-8277-7e3c4ca67efd.png)

**Comment by SakshiShah29** [comment]
I would like to contribute to this issue. I understand the relevant changes needed and will work on them.
