### ISSUE TITLE
Running E2E Tests  is error

### ISSUE THREAD

**Issue by xuzipeng** [FuelLabs/fuels-wallet#576]
### What version of Wallet are you using?

wallet version v0.0.3

### What is happening?

make sure a local test node is running  .  When I was testing  Running E2E Tests ,execute ”pnpm dev:crx“ and "pnpm test:e2e" ，throws an error 。

### steps to reproduce

1 ，pnpm node:dev start  ，This is common.
2,   pnpm dev:crx   throws an error   
![image](https://user-images.githubusercontent.com/13942269/220245995-a643dafc-4efc-4d4f-a6d2-1ab476b883bb.png)
3 .   pnpm test:e2e   throws an error 
       
![image](https://user-images.githubusercontent.com/13942269/220246078-cf29408d-4ecd-45fd-be86-bf71a26398a2.png)

### How it should behave?

Tests should run normally and should not throw exceptions

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

chrome

### What is your browser version?

108.0.5359.124 (arm64)

**Comment by xuzipeng** [comment]
browser is  chrome .

**Comment by qqqzhch** [comment]
I followed the actions here
https://wallet.fuel.network/docs/contributing/running-locally/
pnpm node:dev start
pnpm dev:crx
pnpm test:e2e
Three tests failed
Do these failed tests correspond to features that are in development or do they require any configuration to run successfully?
@luizstacio

**Comment by luizstacio** [comment]
@qqqzhch have you also add the .env config file?

**Comment by qqqzhch** [comment]
> @qqqzhch have you also add the .env config file?
I forgot how to operate the last time, I will get the latest, try again to see
