### ISSUE TITLE
Run Tests E2E in CI/TEST env Mode   error

### ISSUE THREAD

**Issue by xuzipeng** [FuelLabs/fuels-wallet#577]
### What version of Wallet are you using?

wallet version v0.0.3

### What is happening?

at the time of  Run Tests E2E in CI/TEST env Mode  ，The third step ”NODE_ENV=test pnpm test:e2e“ , throw exception .

### steps to reproduce

1. pnpm node:dev start --test    is ok 
2. NODE_ENV=test pnpm build:app   is ok .
3 .NODE_ENV=test pnpm test:e2e    throw exception .
![image](https://user-images.githubusercontent.com/13942269/220248359-0ef9778f-4236-47b3-a912-b689b32cec90.png)

### How it should behave?

It should work and bring up the browser

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

 chrome

### What is your browser version?

chrome : 108.0.5359.124  (arm64)

**Comment by xuzipeng** [comment]
browser is  chrome .

**Comment by luizstacio** [comment]
We made some updates to the test environment. This should not be working now. Also, make sure to follow the tests on the docs: https://wallet.fuel.network/docs/contributing/running-locally/
