### ISSUE TITLE
Create terms of use page

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#582]
[FRO-54](https://linear.app/fuel-network/issue/FRO-54/create-terms-of-use-page)

Add terms of use as a page inside the application on the SignUp flow. This page should be the first one on the Flow. The terms will be rendered inside the component. The content should be markdown or plain HTML, no react.

Design: https://www.figma.com/file/uEckQY4EaQ5rXwyISg6d1g/Fuel-Wallet?node-id=3127%3A16992&t=JIOcIEePnitWrYMS-4

**Comment by tomiiide** [comment]
Blocked because we're waiting for the final Terms of service document.
