### ISSUE TITLE
wallet not detected

### ISSUE THREAD

**Issue by blazebrt** [FuelLabs/fuels-wallet#583]
### What version of Wallet are you using?

0.0.1

### What is happening?

Sometime wallet get crashed and sometime shows PopUp not opened!

### steps to reproduce

Open but blank

### How it should behave?

Just opened and left blanked nothing shows on interface

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

**Comment by luizstacio** [comment]
This is happen with the latest version of the wallet?

**Comment by blazebrt** [comment]
Yes

**Comment by luizstacio** [comment]
@blazebrt  can you update your wallet to the latest version? The version is shown on the sidebar at the bottom. It should be 0.7.2 or bigger.

Let me know if the error persists then we can re-open the issue.
