### ISSUE TITLE
Something is wrong with Fuel Wallet.

### ISSUE THREAD

**Issue by vadka65** [FuelLabs/fuels-wallet#595]
### What version of Wallet are you using?

Fuel Wallet

### What is happening?

Hi, there!

after installing an extension to Google Crome I tried to get test tokens to the wallet.
The message Waiting until more tokens are available  appeared and is sill running.
I did it again many times without any success.
<img width="619" alt="Снимок экрана 2023-02-26 в 09 39 58" src="https://user-images.githubusercontent.com/126389429/221406841-34227f81-63ef-4311-a351-15fdd4c3ecd2.png">

### steps to reproduce

nothing to add

### How it should behave?

nothing to add

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

109.0.5414.119

**Comment by luizstacio** [comment]
@vadka65, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, and making things like the faucet unable to create TXs. This should be solved now, also the faucet was updated to improve the capacity making it faster to release coins. Please let me know if it worked for you now.

**Comment by vadka65** [comment]
Hi, Luiz!Now everything is going well!Thank you!Vadim20 апр. 2023 г., в 00:37, Luiz Estácio | stacio.eth ***@***.***> написал(а):﻿
@vadka65, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, and making things like the faucet unable to create TXs. This should be solved now, also the faucet was updated to improve the capacity making it faster to release coins. Please let me know if it worked for you now.
