### ISSUE TITLE
Centralize new card styling

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#599]
### Motivation

RN we're repeating css styles/structure for all cards in DAPP pages, we should create a new component to centralize this changes

This is the card that is being repeated
![image](https://github.com/FuelLabs/fuels-wallet/assets/8636507/f6b2fe87-7232-4b94-8788-ed53029af8ea)

**Comment by tibi77** [comment]
Hey @LuizAsFight !
I can see that there are some slight deviations in the style of the cards. For example: 
[this](https://github.com/FuelLabs/fuels-wallet/blob/d907dc07491811efa1b3bb434e2a89eb88d841fd/packages/app/src/systems/Core/components/PermissionCard/PermissionCard.tsx#L49) one has the bold font 
```
  cardHeaderText: cssObj({
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$gray12',
  }),
```
and [this](https://github.com/FuelLabs/fuels-wallet/blob/d907dc07491811efa1b3bb434e2a89eb88d841fd/packages/app/src/systems/DApp/pages/AddAssetRequest/AddAssetRequest.tsx#L90-L93) one does not
```
  cardHeaderText: cssObj({
    color: '$gray12',
    fontWeight: '$bold',
  }),
```
shall the solution of this issue fix that as well?(unify all those styles)

**Comment by LuizAsFight** [comment]
@tibi77 they should all look the same
