### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yunggerald25** [FuelLabs/fuels-wallet#601]
### What version of Wallet are you using?

current version

### What is happening?

cant signing message and transaction on wallet.

### steps to reproduce

nil

### How it should behave?

able to allow me signing messsages

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

windows 7

**Comment by luizstacio** [comment]
@yunggerald25, thanks for the report. I have tested the message signing flow on a Windows 7 with Chrome version 108, and it worked correctly.

Please make sure the Wallet you are using is on the latest version. The version is shown on the sidebar at the bottom. It should be 0.7.2 or bigger.

If the error is there yet let me know than we can re-open the issue and work on it.
