### ISSUE TITLE
Confirmation screen does not appear when transferring assets

### ISSUE THREAD

**Issue by netievalage** [FuelLabs/fuels-wallet#603]
### What version of Wallet are you using?

0.1.0

### What is happening?

Although I entered the asset id, amount and recipient address information correctly in the asset transfer section of your how-to-use page, the confirmation screen does not appear in the wallet. There is a problem here.
![Ekran Resmi 2023-02-28 14 38 33](https://user-images.githubusercontent.com/9120577/221847899-d5eb5812-b8d5-46bb-82b1-b7318907c583.png)

### steps to reproduce

Although I entered the asset id, amount and recipient address information correctly in the asset transfer section of your how-to-use page, the confirmation screen does not appear in the wallet. There is a problem here.

### How it should behave?

I don't know

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

### What is your browser version?

1.48.171 Chromium: Version 110.0.5481.177 (Official Build) (x86_64)

**Comment by qqqzhch** [comment]
<img width="1224" alt="WX20230309-213804@2x" src="https://user-images.githubusercontent.com/3917994/224040687-146fc455-04a5-465b-b13d-aa41768661a2.png">
I encountered a similar problem, and after checking, this query has been pending caused

**Comment by luizstacio** [comment]
@Natalie359738, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, making things like the faucet unable to create TXs. This should be solved now.

@qqqzhch thanks for the support here.
