### ISSUE TITLE
fuel not detected on the window!

### ISSUE THREAD

**Issue by kingone88** [FuelLabs/fuels-wallet#605]
### What version of Wallet are you using?

fuel-wallet

### What is happening?

fuel not detected on the window!
![1677637535731](https://user-images.githubusercontent.com/37798621/222029435-a26fdedf-766a-4682-8318-fa1884eb5959.png)

### steps to reproduce

fuel not detected on the window!

### How it should behave?

fuel not detected on the window!

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

版本 108.0.5359.125（正式版本） （64 位）

**Comment by luizstacio** [comment]
I'm closing this issue for inactive.

**Comment by kingone2022** [comment]
如何参与？
