### ISSUE TITLE
The seed phrase is not valid check the words for typos or missing words

### ISSUE THREAD

**Issue by coin95** [FuelLabs/fuels-wallet#607]
### What version of Wallet are you using?

0.7

### What is happening?

The seed phrase is not valid check the words for typos or missing words

### steps to reproduce

Enter your Recovery Phrase

### How it should behave?

The seed phrase is not valid check the words for typos or missing words

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by coin95** [comment]
The seed phrase is not valid check the words for typos or missing words when Enter your Recovery Phrase

**Comment by luizstacio** [comment]
@coin95, thanks for the report, please re-open the issue, providing more information and steps on how to reproduce the issue. This will enable our team to act on it.
