### ISSUE TITLE
Adding custom Assets Failed

### ISSUE THREAD

**Issue by Ejiniemmanuel** [FuelLabs/fuels-wallet#608]
### What version of Wallet are you using?

0.1.0

### What is happening?

I'm trying to add asset, and the response feedback is failed.

### steps to reproduce

It is suppose to be successful

### How it should behave?

It should detect the wallet and add automatically after approving.

### What os are you seeing the problem on?

None

### What browser?

Chrome

**Comment by Bimzzy** [comment]
I'm having similar problem trying to add asset

**Comment by luizstacio** [comment]
Hi @kachi90 and @Bimzzy thanks for the issues;
You need to update the Wallet to version 0.7.0. This is the current version available on wallet.fuel.network.
