### ISSUE TITLE
When I try to 'add assets' on How to use page I receive the message: R.addAssets is not a function. I have been trying but anyway receive the same message.

### ISSUE THREAD

**Issue by mrhodlerDanill** [FuelLabs/fuels-wallet#612]
https://github.com/FuelLabs/fuels-wallet/blob/6a32805c2241c9bc1ec2a1599013e49619572649/packages/docs/examples/AddAssets.tsx#L39-L40

**Comment by luizstacio** [comment]
@mrhodlerDanill, this feature is available only on the last version.

Can you confirm the version of your wallet is 0.7.0? You can find this info by opening the sidebar of the wallet. The version is at the bottom.

<img width="357" alt="Screenshot 2023-03-08 at 16 01 33" src="https://user-images.githubusercontent.com/3941923/223811371-3dfd31cf-0f97-46c4-b578-f47aa0a01d83.png">

**Comment by mrhodlerDanill** [comment]
Hi! Hm, It seems to me I used the old version:
![image](https://user-images.githubusercontent.com/108091988/226199252-1a03165e-3ee7-40b2-936a-94f9cefefccd.png)

**Comment by mrhodlerDanill** [comment]
Where can I find the last version or how to upgrade to the current one? I downloaded it from https://wallet.fuel.network/docs/install/ but it

**Comment by mrhodlerDanill** [comment]
but is was the 0.1.0

**Comment by LuizAsFight** [comment]
@mrhodlerDanill can you try removing the extension, then adding it again from zip file downloaded in https://wallet.fuel.network/docs/install/ ?

**Comment by luizstacio** [comment]
Please make sure the Wallet you are using is on the latest version (v0.7.2). The version is shown on the sidebar at the bottom. It should be 0.7.2 or bigger.

**Comment by mrhodlerDanill** [comment]
Thanks, I really had the old version.
