### ISSUE TITLE
Transaction Preview fail to operations when the sender equal the receiver

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-wallet#613]
[FRO-57](https://linear.app/fuel-network/issue/FRO-57/transaction-preview-fail-to-operations-when-the-sender-equal-the)

### Motivation

I think users should be notified that they are trying to run a transaction whose receiver address is the same as the wallet's address they're running the transaction from.

### Usage example

I tried sending ETH to myself and the "Approve Transaction" page looks like this:
![image](https://user-images.githubusercontent.com/17943891/222975384-0ee65f3d-50f0-4e19-9b76-189475b91921.png)

### Possible implementations

I've created a quick mockup:
![image](https://user-images.githubusercontent.com/17943891/222975921-3f6a71a5-e672-4f1a-9c90-9e3019ecf39e.png)

Another solution might be to show a warning dialog when the user clicks "Approve".

**Comment by qqqzhch** [comment]
I'll try to do this
I think this solution is a little better
add text tip NOTE:the sender and receiver address are same

**Comment by qqqzhch** [comment]
![image](https://user-images.githubusercontent.com/3917994/225917472-a7c044de-c2ab-4ffd-baac-d03e5bee5fbe.png)
After looking for the relevant code.
I plan to add a component to display an tip message that needs to be displayed here if the status of the transaction is a failure.
