### ISSUE TITLE
transaction not loading since Testnet 3

### ISSUE THREAD

**Issue by Matt1338air** [FuelLabs/fuels-wallet#626]
### What version of Wallet are you using?

Testneet Beta 3

### What is happening?

![image](https://user-images.githubusercontent.com/128389116/226903508-37919590-3bac-4545-a545-3cbea9d75881.png)

Doesnt confirm transaction

### steps to reproduce

![image](https://user-images.githubusercontent.com/128389116/226903599-dd41a0d8-f385-470a-b783-b515f05be1df.png)

click the button on:

https://wallet.fuel.network/docs/how-to-use/

### How it should behave?

Should just approve

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

latest

**Comment by LuizAsFight** [comment]
@Matt1338air , thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution. This should be solved now.
