### ISSUE TITLE
Gives an error message

### ISSUE THREAD

**Issue by GFONLINENEW** [FuelLabs/fuels-wallet#631]
### What version of Wallet are you using?

New

### What is happening?

Gives an error message

### steps to reproduce

Check it working Gives an error message

### How it should behave?

Check if it works translation 0.00001

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

Version 1.49.128 Chromium 111.0.5563.110

**Comment by LuizAsFight** [comment]
@GFONLINENEW , thanks for the report. I will be closing this issues as it doesn't have enough details. Please open other issue with more info if you still have a problem.
