### ISSUE TITLE
Add account name on home page and transaction view

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#632]
Currently, the account name is only visible on the account list. This task should create a component that gets the account's name from the account list, and if not found, it shows an unknown label.

<img width="743" alt="Screenshot 2023-03-23 at 10 52 00" src="https://user-images.githubusercontent.com/3941923/227225470-8767fb3a-9b71-4cb8-b2e5-65c531435380.png">
<img width="524" alt="Screenshot 2023-03-23 at 10 53 46" src="https://user-images.githubusercontent.com/3941923/227225496-e0dfbe27-2b89-4d25-98ae-6505b8c57c93.png">

**Comment by LuizAsFight** [comment]
left is design, right is current PR implementation

notice that: 
1- "Account 1" font size is bigger in right.
2- "fuel...asd" font size is bigger in right
3- "ETH 0.00" font size is smaller in right
4- spacing to the bottom after "ETH 0.00" is smaller in right
5- eye icon is a bit smaller in right


<img width="718" alt="image" src="https://user-images.githubusercontent.com/8636507/229011327-67965607-3519-4ace-9ba4-df7cfc753a37.png">
