### ISSUE TITLE
Faucet claim

### ISSUE THREAD

**Issue by Mickoski** [FuelLabs/fuels-wallet#635]
### What version of Wallet are you using?

0.7.1

### What is happening?

I was trying to request faucet on https://fuellabs.github.io/swayswap/welcome/create-wallet but it keeps coming up with errors "invalid faucet request''

### steps to reproduce

If its a bug from your end, kindly help fix it. The previous testnet versions was so sleek and stress free, but this, I've been on it for a while now. 

### How it should behave?

I expected it to go through with no stress. I tried everything I could to see if I was doing something wrong but I can't find nothing. fuel1lj9twh7spn9pmg35f70gca44arfyy9yqnkc6e2e4r2s9cmhf3zzq8shrwk
That's my wallet 

### What os are you seeing the problem on?

Android Mobile

### What browser?

Other

### What is your browser version?

Mises 423031712 version

**Comment by Mickoski** [comment]
fuel1lj9twh7spn9pmg35f70gca44arfyy9yqnkc6e2e4r2s9cmhf3zzq8shrwk

Thats my wallet

**Comment by luizstacio** [comment]
@Mickoski, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution. Making things like the faucet unable to create TXs. This should be solved now.

**Comment by Mickoski** [comment]
Alright, I'll try it out and give further feedback
