### ISSUE TITLE
Wallet is very slow, transactions are failing

### ISSUE THREAD

**Issue by GloriouslifeWM** [FuelLabs/fuels-wallet#639]
### What version of Wallet are you using?

0.7.1

### What is happening?

![Screenshot_2023_0328_165457](https://user-images.githubusercontent.com/107487643/228227218-6acd884b-72fd-4bf3-a329-66496cb1e748.jpg)
When I try to transfer assets, the wallet keep processing and after a long time approve the transaction, but still the transfer transaction is keep failing due to wallet slowness

### steps to reproduce

To make the wallet fast

### How it should behave?

Transactions should be fast

### What os are you seeing the problem on?

Android Mobile

### What browser?

Other

### What is your browser version?

Mises browser

**Comment by luizstacio** [comment]
@GloriouslifeWM, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution. This should be solved now.
