### ISSUE TITLE
Wallet extension

### ISSUE THREAD

**Issue by alex159159** [FuelLabs/fuels-wallet#646]
### What version of Wallet are you using?

Last

### What is happening?

I cannot open it from extension, it disappeared

### steps to reproduce

It disappeared from extension

### How it should behave?

It disappeared from extension

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

### What is your browser version?

Brave

**Comment by luizstacio** [comment]
@alex159159 Thanks for the report. This is expected behavior from browsers because of the way the installation is done by a zip file. In the future, it will not be true once the installation is done by Chrome Web Store the Wallet should not disappear from the extensions.

**Comment by alex159159** [comment]
Hi,

thank you for the reply. Anyway, fuel wallet with swayswap is very quick in test mode.

Bye.

N.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
