### ISSUE TITLE
Bug Report with wallet

### ISSUE THREAD

**Issue by vadka65** [FuelLabs/fuels-wallet#647]
### What version of Wallet are you using?

not find

### What is happening?

Hi there! I tried 3 times to transfer test ETH in Wallet fuel158hlkculpkhayunep5w7c5yhnr7ryz4gjyaqv62vpeljmul6vv6sv2enyw.
Transaction failed  with reason Window closed by inactivity after 5 minutes. Before it transfer was approved 

### steps to reproduce

![Снимок экрана 2023-03-29 в 17 26 38](https://user-images.githubusercontent.com/126389429/228571046-a535aca6-1aa5-451d-aa79-d66dbb8c82ca.png)

### How it should behave?

-

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

109.0.5414.119

**Comment by luizstacio** [comment]
@vadka65, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow as the Wallet closes after 5 minutes. This should be solved now.
