### ISSUE TITLE
Transfer Faild

### ISSUE THREAD

**Issue by hariyanviyt** [FuelLabs/fuels-wallet#649]
### What version of Wallet are you using?

Version: 0.7.1

### What is happening?

During transfer ETH to other wallet it shown failed. I have try too many time but the issue is as it is.
also it is taking too much time. 

### steps to reproduce

Window closed by inactivity after 5 minutes!
Check it working
X
Failed
0x0000000000000000000000000000000000000000000000000000000000000000
fuel1a6msn9zmjpvv84g08y3t6x6flykw622s48k2lqg257pf9924pnfq50tdmw
0.001
Transfer

### How it should behave?

![error](https://user-images.githubusercontent.com/129389175/228818869-57898b86-89ec-42e8-87a7-01458a9dedc0.JPG)

### What os are you seeing the problem on?

None

### What browser?

Brave

### What is your browser version?

Brave is up to date Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@hariyanviyt, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow as the Wallet closes after 5 minutes. This should be solved now.
