### ISSUE TITLE
Wallet bug

### ISSUE THREAD

**Issue by xiaoliyubaby** [FuelLabs/fuels-wallet#654]
### What version of Wallet are you using?

0.7.1

### What is happening?

Today I reinstalled the latest version of the beta3 wallet, and then followed the process to claim the test coins and succeeded, but the received test coins are still not displayed in my wallet. I tried a few more times, and it is still the same. Then I cleared the browser's cache, but it didn't work. So I changed to another computer and imported the wallet. At this time, the wallet displayed the six test coins I received before, totaling 3eth.
![image (4)](https://user-images.githubusercontent.com/107856385/229112325-246225bc-02e2-42c5-8416-684d480b425e.png)
![微信图片_20230331194905](https://user-images.githubusercontent.com/107856385/229112485-86aa6ab0-c31c-4924-94ed-6d691c945f11.jpg)

### steps to reproduce

see the happening

### How it should behave?

.....

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.95 (64)

**Comment by luizstacio** [comment]
@h805846716 Thanks for reporting. This error should be solved on the latest Wallet v0.7.2, We have tested it on a device with the same config Windows on Chrome v108. Let me know if the error persists then we can re-open the issue and work on it.
