### ISSUE TITLE
faucet token did not arrive in newly created wallet

### ISSUE THREAD

**Issue by Desposyniunchained** [FuelLabs/fuels-wallet#655]
### What version of Wallet are you using?

0.7.1

### What is happening?

OS Windows 10
Good browsers

I set up the wallet according to the instructions and then picked up the faucet tokens. They will show up in the block explorer under my wallet address but not in the wallet.
I was able to test the wallet successfully until I got to the point of "Transferring assets", where I was then shown that I had no assets. The green button gets stuck on "Loading".

### steps to reproduce

Install Wallet
click on Get faucets in Wallet
past wallet address into the address field on the faucet page
click Give Me Ether

### How it should behave?

Test ETH should arrive in Wallet

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

v1.49.132 (Mar 28, 2023)

**Comment by luizstacio** [comment]
@Desposyniunchained, thanks for reporting, please try updating your Wallet to the latest version 0.7.2, this error looks to be related to a mismatch between the wallet and faucet network.
