### ISSUE TITLE
Transfering assets

### ISSUE THREAD

**Issue by mecitkeskin** [FuelLabs/fuels-wallet#656]
### Motivation

on the wallet transfering asset not working  for two days.

### Usage example

and for asset transfering wallet could be sign message. wallet didn't want sign message. and transfer is frozed.

### Possible implementations

smart contarct is not working.

**Comment by luizstacio** [comment]
@mecitkeskin, thanks for reporting. I don't know what exactly the error you are facing is. But is related to the network instability from the past weeks, causing transactions to be very slow and not finishing the execution. This should be solved now.

Cause the error persists, please open a new issue with some more details for the team to be able to act on it.

**Comment by mecitkeskin** [comment]
Thanks bro for attention. I am not professional on the cripto sector. But on your Wallet tx didn’t sign on Wallet. I think it’s a mistake. I didn’t found writing where this issue. May be Discord. On the page writed the ‘send the github’. I writed it on github.  I Can delete it. Thanks bro. iPhone’umdan gönderildiLuiz Estácio | stacio.eth ***@***.***> şunları yazdı (19 Nis 2023 21:59):﻿
@mecitkeskin, thanks for reporting. I don't know what exactly the error you are facing is. But is related to the network instability from the past weeks, causing transactions to be very slow and not finishing the execution. This should be solved now.
Cause the error persists, please open a new issue with some more details for the team to be able to act on it.
