### ISSUE TITLE
history section bug

### ISSUE THREAD

**Issue by mamikm** [FuelLabs/fuels-wallet#658]
### What version of Wallet are you using?

0.71

### What is happening?

I tried sending ethereum to my own address and after sending it the past transactions section started showing as a black screen

### steps to reproduce

The past transactions section should be improved

### How it should behave?

Should show past transactions normally

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

1.49.132

**Comment by luizstacio** [comment]
@mamikm I have tested it here on the latest version of Wallet 0.7.2, and it worked. The transaction history also shows the transaction correctly. We have an issue already tracked about the TX Preview page that is not displaying correctly when the Account is sending assets to itself, but this looks to be a different issue from what you are reporting.

Please try to update your Wallet to the latest version. To know what version you are, look in the sidebar at the bottom. It should be 0.7.2 or bigger. In case the issue persists let me know and we can re-open the issue to follow up on this.
