### ISSUE TITLE
Wallet doesn't work

### ISSUE THREAD

**Issue by 7robson7** [FuelLabs/fuels-wallet#660]
### What version of Wallet are you using?

Fuel 0.7.1

### What is happening?

![fuel doesn't work](https://user-images.githubusercontent.com/129618391/229306654-d0744875-f8a3-45c6-9174-cabbe2b1d619.png)
My wallet doesn't work

### steps to reproduce

.

### How it should behave?

![wallet doesn't work](https://user-images.githubusercontent.com/129618391/229306737-5ae66dec-967f-49da-b62d-2f7d4c0f2e00.png).
Failed to access file It may have been moved, edited or deleted.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Other

### What is your browser version?

Brave

**Comment by luizstacio** [comment]
@7robson7, thanks for reporting. Please make sure the Wallet you are using is on the latest version. The version is present on the sidebar at the bottom. It should be 0.7.2 or bigger.

This error also looks related to the zip file not existing more, this can happen if you delete the zip file from the place it was. These issues should be resolved once we release on App on Chrome Web Store you can track it here: #714 

Please in case the error still exists with the newer version, let me know and we can re-open the issue.
