### ISSUE TITLE
fuel https://fuellabs.github.io/swayswap/ cannot log in to the wallet

### ISSUE THREAD

**Issue by terrypanda123** [FuelLabs/fuels-wallet#661]
### What version of Wallet are you using?

fuel https://fuellabs.github.io/swayswap/ cannot log in to the wallet

### What is happening?

fuel https://fuellabs.github.io/swayswap/ cannot log in to the wallet

### steps to reproduce

fuel https://fuellabs.github.io/swayswap/ cannot log in to the wallet

### How it should behave?

fuel https://fuellabs.github.io/swayswap/ cannot log in to the wallet

### What os are you seeing the problem on?

None

### What browser?

None

### What is your browser version?

google chrom

**Comment by luizstacio** [comment]
@terrypanda123, thanks for the report. Please make sure the Wallet you are using is on the latest version the version is shown on the sidebar at the bottom. It should be 0.7.2 or bigger.

As I don't have much information about the issue it's hard for the team to act on it, please re-install the wallet with the latest version and check if is working right now. In case the issue still exists, open a new issue with more detailed information or maybe a screen(record/print).
