### ISSUE TITLE
Test tokens not coming

### ISSUE THREAD

**Issue by Jaxqas** [FuelLabs/fuels-wallet#662]
### What version of Wallet are you using?

Fuel Wallet 0.7.1

### What is happening?

Test tokens not coming

### steps to reproduce

Requested test tokens. The transaction is in the hash, but there are no tokens on the wallet fuel13c9rn9rgdepcckwj396pq4pqscqw8lm2sshwf3ztll4m3n0tp2usykkktz

### How it should behave?

I want to see the tokens on my wallet to continue testing

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
@Jaxqas, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, and making things like the faucet unable to create TXs. This should be solved now.

Please let me know if the error still exists then we can re-open the issue and follow up.
