### ISSUE TITLE
Transfer failed

### ISSUE THREAD

**Issue by Argentino110** [FuelLabs/fuels-wallet#663]
### What version of Wallet are you using?

0.17.7

### What is happening?

Can't transfer assets. Always failed. 
![Fuel](https://user-images.githubusercontent.com/107501832/229356346-8a994c09-618f-4d69-a925-9c423bf79ee8.jpg)

### steps to reproduce

I click transfer, then loading, then failed and appear the text you can see at the top right. 

### How it should behave?

I expected the message from wallet - approved then transaction completed. As it was previously, 5 days ago, 9 and 11 days ago. (please see history)
![Wallet history](https://user-images.githubusercontent.com/107501832/229356677-506e38aa-979a-45e7-b6fd-055157bcd872.jpg)

### What os are you seeing the problem on?

Windows Desktop

### What browser?

None

### What is your browser version?

Google chrome canary

**Comment by luizstacio** [comment]
@Argentino110, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow with errors like this as the network responded with 500 errors. This should be solved now.
