### ISSUE TITLE
Hide the faucet button when the network not support it

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#668]
[FRO-53](https://linear.app/fuel-network/issue/FRO-53/hide-the-faucet-button-when-the-network-not-support-it)

When a user doesn't have assets we show a button to the faucet, this button is linked to the current config faucet, but this faucet could be different from the network selected making it not work as expected.

What we should do is just show the faucet when the correct network is selected.

Example:
- If the wallet has a faucet for beta-3 and the user changes the network to localhost we should hide the faucet button.

**Comment by nedsalk** [comment]
Rather than hiding it, what do you think of perhaps disabling the button and putting a tooltip that explains why it's disabled?

**Comment by luizstacio** [comment]
> Rather than hiding it, what do you think of perhaps disabling the button and putting a tooltip that explains why it's disabled?

The faucet is a feature that is only possible on a specific network. If users are on the mainnet as an example, it should not be displayed the faucet as it's only for development.
