### ISSUE TITLE
faucet bug

### ISSUE THREAD

**Issue by edikbass777** [FuelLabs/fuels-wallet#669]
### What version of Wallet are you using?

0.7.2

### What is happening?

When I'm testing both faucets (the SwaySwap one, and the faucet-beta-3.fuel.network), none of them are working. The receive Ether button just keeps endlessly loading and at the end of the day I get nothing but this errors
1: "Failed to submit transaction with error: Response errors; Transaction is not inserted. UTXO is not existing: 0xffdc1e1d44dfdf5b169691ea17b08b178728d6609c93dce6e16dcb8fd280c10b01"
2: "Failed to submit transaction with error: Response errors; Transaction is not inserted. More priced tx 0x9384963263e33e3d5a536b59c5d50b9533149ae62f13163b63d47ef610400f70 already spend this UTXO output: 0x63863116dbc37ed969cd7e5c6c8a60f3557a027710d76bd407b7980b6eaa227501"

### steps to reproduce

Freshly created wallet, localhost ip, clean browser cache

### How it should behave?

Having used it in Beta-2 testnet, I know that it just should send testnet tokens to my wallet in the matter of seconds

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 111.0.5563.64 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@edikbass777, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, making things like the faucet unable to create TXs. This should be solved now.
