### ISSUE TITLE
Transferring is performed not from the current wallet account, but from the first

### ISSUE THREAD

**Issue by doristeo** [FuelLabs/fuels-wallet#670]
### What version of Wallet are you using?

0.7.2

### What is happening?

Transferring is performed not from the current wallet account, but from the first (сreated when installing the wallet) in this page https://wallet.fuel.network/docs/how-to-use/.

### steps to reproduce

![2023-04-05_18-53-09](https://user-images.githubusercontent.com/3895507/230136243-5cdac5b6-74a0-4e9f-8d4e-e7093b0511d9.png)

### How it should behave?

1. Change account in the wallet.
2. Transfering assets https://wallet.fuel.network/docs/how-to-use/
3. Look at screenshot.

### What os are you seeing the problem on?

None

### What browser?

None

**Comment by luizstacio** [comment]
@doristeo, thanks for the report. This is expected behavior, if you look at the code sample of Transfer Asserts, it uses the first account on the accounts connected list to submit the transfer.

https://wallet.fuel.network/docs/dev/getting-started/#transfering-assets
```ts
const account = accounts[0];
const wallet = await fuel.getWallet(account);
```
