### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by oruk61** [FuelLabs/fuels-wallet#672]
### What version of Wallet are you using?

Fuel Wallet

### What is happening?

I tested Fuel Wallet by following the orders. Those are working well. When I tried to receive from another test wallet (in goerly test net connecting by metamask), it did not work properly. Maybe you know that or not. I wanted to report this situation. Regards.

### steps to reproduce

It was just a try.

### How it should behave?

It's written at the above section.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Micrososft Edge

**Comment by luizstacio** [comment]
@oruk61, thanks for reporting, Fuel Network is not directly connected to goerly testnet. To transfer assets from the goerly testnet to Fuel Network, you must do it through a bridge. Currently, no UI is available for it.

If you have done this by the FuelMessagePortal contracts and the assets still do not show on the balance please open a new issue reporting that assets bridged from ETH are not shown on the Wallet and we are going to follow up on that.

**Comment by oruk61** [comment]
I could correct as you wrote. Thank you Mr. Estacio. O.Utlu
________________________________
Gönderen: Luiz Estácio | stacio.eth ***@***.***>
Gönderildi: 19 Nisan 2023 Çarşamba 20:59
Kime: FuelLabs/fuels-wallet ***@***.***>
Bilgi: Orhan Utlu ***@***.***>; Mention ***@***.***>
Konu: Re: [FuelLabs/fuels-wallet] Transaction (Issue #672)


Closed #672<https://github.com/FuelLabs/fuels-wallet/issues/672> as completed.
