### ISSUE TITLE
can't disconnect wallet

### ISSUE THREAD

**Issue by hussiwong** [FuelLabs/fuels-wallet#673]
### What version of Wallet are you using?

beta3

### What is happening?

I opened the fuel wallet beta2, and  connected the web  https://fuellabs.github.io/swayswap .  It can't mint the assets (step 4) ,because the wallet haven't update to beta3.  

### steps to reproduce

I opened the fuel wallet beta2, and  connected the web  https://fuellabs.github.io/swayswap .  It can't mint the assets (step 4) ,because the wallet haven't update to beta3.  But after I updated the wallet, I reconnect the wallet and open the swaysway. The web is direct jumping to step4 (mint assets), and still can't work  and can't disconnect the wallet to start again.

### How it should behave?

need a  disconnect button. 

### What os are you seeing the problem on?

None

### What browser?

Chrome

**Comment by luizstacio** [comment]
@hussiwong, thanks for reporting. Please make sure the Wallet you are using is on the latest version the version is shown on the sidebar at the bottom. It should be 0.7.2 or bigger.

The current version is already compatible with the beta-3 network and should work correctly.
