### ISSUE TITLE
Swayswap bug?

### ISSUE THREAD

**Issue by andcip656** [FuelLabs/fuels-wallet#677]
### What version of Wallet are you using?

Testnet Beta 3

### What is happening?

I am using swayswap and when I try to mint assets it says that there were an "error" 

### steps to reproduce

I am on the swayswap page doing the first steps, so I am aware it could be a normal problem of  connection with a new wallet. In the image you can see the loading which will not go well.
![swayswap bug](https://user-images.githubusercontent.com/129203781/230717506-5348b7bd-e970-4153-bdb2-1705c049ce35.png)

### How it should behave?

I expected that it would have work.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
@andcip656, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow with errors like this. This should be solved now, please open a new issue in case the error still exists.

**Comment by andcip656** [comment]
Hi, thanks for the response, but now I actually can't go on my fuel wallet.
Yesterday I tried to login but it was like it has been uninstalled. So now
I eliminated the google extension and I am trying to reinstall my wallet.

Il giorno mer 19 apr 2023 alle ore 19:49 Luiz Estácio | stacio.eth <
***@***.***> ha scritto:
