### ISSUE TITLE
Dapps not able to connect with fuel wallet

### ISSUE THREAD

**Issue by zkfi2** [FuelLabs/fuels-wallet#680]
### What version of Wallet are you using?

0.0.1

### What is happening?

Tried lot of times to connect dapps with fuel wallet no popup window is formed. 

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.
Context
popup.html

### steps to reproduce

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Either the 'unsafe-inline' keyword, a hash ('sha256-aRGRodzo2c9wFwcNMmeGOy0lMrlxR5KcUJUUj8ODA24='), or a nonce ('nonce-...') is required to enable inline execution.

### How it should behave?

nothing work

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
@zkfi2, thanks for reporting. Please make sure the Wallet you are using is on the latest version, and the version is present on the sidebar at the bottom. It should be 0.7.2 or bigger. The older versions had the error log you posted, so I supposed you are on an older version.

Also, DApps can have errors in their code, which should be reported directly to the team responsible for it.
