### ISSUE TITLE
History not showing

### ISSUE THREAD

**Issue by Fooferke** [FuelLabs/fuels-wallet#681]
### What version of Wallet are you using?

0.7.2

### What is happening?

Selecting history is only showing a black screen.

Brave browser.
<img width="407" alt="Scherm­afbeelding 2023-04-10 om 14 12 53" src="https://user-images.githubusercontent.com/130367545/230899550-226c26af-835f-41f8-8e13-8a9974d2f18d.png">
<img width="407" alt="Scherm­afbeelding 2023-04-10 om 14 13 08" src="https://user-images.githubusercontent.com/130367545/230899569-9e2cb4ea-fba9-4087-b822-7b1095cb03f3.png">

### steps to reproduce

Same behavior every time history is selected

### How it should behave?

Show the history of all transactions

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

### What is your browser version?

Versie 1.50.114 Chromium: 112.0.5615.49 (Officiële build) (arm64)

**Comment by luizstacio** [comment]
@Fooferke, thanks for reporting this issue. Can you provide us with the error logs from the extension? You can see these errors by going to the `extensions management` on the same page you used to install, and then it should have a `Errors` button. Just copy and paste that here, and ensure only data you are willing to share are present on the log.
