### ISSUE TITLE
Transfer assets doesnt work on docs

### ISSUE THREAD

**Issue by mmiller4255** [FuelLabs/fuels-wallet#682]
### What version of Wallet are you using?

Newest

### What is happening?

Clicking the transfer asset button, it pulls up Fuel wallet and then is an infinite loading screen on wallet

### steps to reproduce

on docs, the "check it working" 'transfer asset' button

### How it should behave?

not a infinite load

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
@mmiller4255, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow as the Wallet closes after 5 minutes. This should be solved now.
