### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by taher636465** [FuelLabs/fuels-wallet#688]
### What version of Wallet are you using?

Version: 0.7.2

### What is happening?

https://fuellabs.github.io/swayswap/ and swap assets

It does not work properly

### steps to reproduce

f

### How it should behave?

f

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

chrome last version

**Comment by luizstacio** [comment]
@taher636465 Thanks for reporting. On the following issues, please provide more information about the error to enable the team to understand better and be able to act on it.

Our network was unstable in the past weeks, causing transactions to be very slow and not finishing the execution. I will assume this was the issue you were seen. Please open a new issue in case you are seen this errors yet with more detailed information.
