### ISSUE TITLE
wallet and dap 

### ISSUE THREAD

**Issue by Sujal9679** [FuelLabs/fuels-wallet#689]
### What version of Wallet are you using?

0.7.1

### What is happening?

wallet and dap are not working some times its worked but verry slow  please do something for this problem  

### steps to reproduce

update wallet and dap

### How it should behave?

its slow and stack

### What os are you seeing the problem on?

Windows Desktop

### What browser?

None

**Comment by Sujal9679** [comment]
do quick

**Comment by luizstacio** [comment]
@Sujal9679, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow with errors like this as the network responded with 500 errors. This should be solved now.
