### ISSUE TITLE
STUCK IN MINT ASSET

### ISSUE THREAD

**Issue by Greys11** [FuelLabs/fuels-wallet#694]
### What version of Wallet are you using?

Version: 0.7.2

### What is happening?

is stucking in mint asset i wait for 1 hours more
`to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content-script/contentScript.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/sourcemaps/inject.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://enabgbdfcbaehmbigakijjabdpdnimlg/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/sourcemaps/inpage.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content-script/inpageSol.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/utils.esm.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/content-script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`

### steps to reproduce

i tried to refresh web - Disconnecting App and change my dns/network it still stucking

### How it should behave?

i got my faucet and try the swayswap

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

### What is your browser version?

Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@Greys11, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution. Making things like the faucet unable to create TXs. This should be solved now.
