### ISSUE TITLE
Wallet not work in fuelart.io

### ISSUE THREAD

**Issue by VitaliiZhukovsky** [FuelLabs/fuels-wallet#701]
### What version of Wallet are you using?

0.0.1

### What is happening?

Wallet not work in fuelart.io

### steps to reproduce

Transaction not a work. Wallet is exit and get error

### How it should behave?

Write transaction

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 109.0.5414.129 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@VitaliiZhukovsky, thanks for reporting. This problem could be related to many factors. One is the stability of the network or other issues related to the application itself.

Please chat with the FuelArt team directly on their channels https://fuelart.io/ as the issue could be related to the DApp and not to the Fuel Wallet.
