### ISSUE TITLE
Fuel wallet automatically removed from Chrome

### ISSUE THREAD

**Issue by id120189** [FuelLabs/fuels-wallet#702]
### What version of Wallet are you using?

0.7.2

### What is happening?

After installation of Fuel Wallet it was removed from Chrome browser after some time

### steps to reproduce

1. Install the wallet on Chrome browser
2. Make couple of transactions
3. Check after couple of days if wallet is visible in extensions

### How it should behave?

Wallet should not be removed from any browser

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 112.0.5615.49 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@id120189 this is expected behavior from browsers and the installation is done by a zip file. In the future, it will not be true once the installation is done by Chrome Web Store.
