### ISSUE TITLE
"Insufficient Funds Error"

### ISSUE THREAD

**Issue by ignaaaa29** [FuelLabs/fuels-wallet#703]
### What version of Wallet are you using?

0.7.1

### What is happening?

My wallet says I have insufficient funds of an asset, when I do not.

### steps to reproduce

In the wallet of the chrome extension:
1) Send.
2) Enter a number, for example 0.1 (but make sure you do have more than 0.1 of, for example ETH, in your wallet). You may read "Insufficient funds" in red below.
3) Select the asset, make sure you have more than 0.1 ETH (in this example) in your wallet. 

And still will shows in red "Insufficient funds", when it should not.

### How it should behave?

You still may be able to send the funds if you wish to do so, just is a message which is incorrect because I do have the sufficient funds.
I did the example with 0.1 ETH and I have more funds in my wallet. You may check if you wish so: https://fuellabs.github.io/block-explorer-v2/beta-3/#/address/fuel1mjje6tx6e2sz7qm4m0nd3tuwqfn0zhf5gwua76j5639dy3sd3gfsqzyarr

### What os are you seeing the problem on?

None

### What browser?

None

**Comment by luizstacio** [comment]
This error should appear only when the amount on the input is bigger than your balance + gas fee costs. Testing here I was not able to simulate the error.

Can you provide a screen record for us to understand better the issue?

**Comment by ignaaaa29** [comment]
Yes, please check the screenshot.

![Insufficient funds error](https://user-images.githubusercontent.com/118273941/233802037-2ee38e17-6c9e-4fe4-a273-3cbba218aeb8.png)

Let me know if you have any doubts or comments.
