### ISSUE TITLE
Transfer DAI from address A to address B

### ISSUE THREAD

**Issue by yuanmangguo** [FuelLabs/fuels-wallet#705]
[FRO-51](https://linear.app/fuel-network/issue/FRO-51/transfer-dai-from-address-a-to-address-b)

### What version of Wallet are you using?

Fuel Wallet 0.7.2

### What is happening?

Only ETH can be transferred, other assets cannot be transferred.

### steps to reproduce

Transfer DAI from address A to address B

### How it should behave?

Transfer DAI from address A to address B

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 112.0.5615.86 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@yuanmangguo, thanks for the report I have tested here in found the issue, you can track it on this issue.
