### ISSUE TITLE
When opening accounts via sidebar accounts link device is working as double tap

### ISSUE THREAD

**Issue by Talisson007** [FuelLabs/fuels-wallet#706]
### What version of Wallet are you using?

Versão 0.7.1

### What is happening?

when you have 3 accounts and you go to configuration and when you click on the account it only opens the middle account as if you were double-clicking

### steps to reproduce

https://user-images.githubusercontent.com/131008173/232530642-c35b3239-9496-4579-bb62-553eaa95683d.mp4

### How it should behave?

when you click on the account, the accounts should appear for you to choose from and not choose automatic only the middle account.

### What os are you seeing the problem on?

Android Mobile

### What browser?

Other

### What is your browser version?

Kiwi Browser 112.0.5615.135

**Comment by luizstacio** [comment]
@Talisson007, thanks for the report.

We have tested it on a Google Pixel 7 with the Kiwi browser but were not able to replicate it only if we double tap on the menu item. This looks like a bug on the Device where the tap is passing the click to the background page, maybe in how it handles the touch. Can you inform us of the kind of device to enable us to test? 

Contributions are welcome as the Kiwi/Mobile browser is not the top priority right now. But you can track when we fix on this issue.
