### ISSUE TITLE
Adding a network

### ISSUE THREAD

**Issue by danevqq** [FuelLabs/fuels-wallet#708]
### What version of Wallet are you using?

Version: 0.7.2

### What is happening?

Incorrectly adding networks

### steps to reproduce

When adding a custom network, I specified a name and inserted a link to a random tweet instead of the network URL, but the network was added to the wallet. I switched to that network, and even requested test tokens through the wallet tap, but they came to the main Testnet Beta 3 network

### How it should behave?

Checking for a valid URL should work better and reject non-existent RPCs

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

### What is your browser version?

Version 1.50.114

**Comment by danevqq** [comment]
Just in case my Fuel address:
fuel1hv0vcv8m4q3ek5v0tgjcj6vgudxt7c0ghqgagz37j7rs7s4qggdqqzjgwt

My Discord name:
LogosWGP#4707

My MetaMask address:
0x85A76add66EA3CfD94803Aaa2d60ca1985cCaB18

**Comment by luizstacio** [comment]
Thanks, @danevqq, for reporting. This are known issues and will be solved on #610 #611
