### ISSUE TITLE
The wallet is not displayed

### ISSUE THREAD

**Issue by Kindavr** [FuelLabs/fuels-wallet#709]
### What version of Wallet are you using?

Perhaps, the last version because I used official site to install the wallet

### What is happening?

The website doesn't recognize that I've already installed the wallet and asked me to do it again every time. I've redone it several times but nothing has changed. Therefore, I can't sign my wallet on this website and finish the testnet correspondingly

### steps to reproduce

I opened the official website and put the button "download the wallet", than I created my wallet after that I tried to connect my wallet to the official site to complete so-called "request connection"; however, nothing worked.

### How it should behave?

The website should recognize that I've already have the wallet and give me the possibility to complete "request connection".

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by Ophelia36** [comment]
Hi @Kindavr  I suggest you contact wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by luizstacio** [comment]
Can you provide more info on the version of Chrome you are using to enable us to emulate it? Testing the flowing current on Chrome's Latest version on Windows works as expected.

Some points to note;
- Make sure to set up the Wallet before coming back to the flow, a Wallet is only recognized to connection after the Wallet is set up.
