### ISSUE TITLE
Wallet issues

### ISSUE THREAD

**Issue by steveelon9** [FuelLabs/fuels-wallet#710]
### Motivation

I think Team need to create a set of time lock wallet on Fuel.  It's really uncomfortable

### Possible implementations

I am really uncomfortable when test Fuel. wallet is always lock while 2 minutes.

**Comment by luizstacio** [comment]
Thanks for reporting. The unlock should be in a window of 15 minutes, but it looks like it's locking before this time. 
Issue tracking the bug: https://github.com/FuelLabs/fuels-wallet/issues/712

**Comment by steveelon9** [comment]
Okay. It's Great
Now I can comfortabel to test on Fuel.

Thank you!
*NGO PHUOC NHAN*
*Marketing Major*
*Email*: ***@***.***
*SĐT*: 0702259883
*“I like to use the hard times in the past to motivate me today.” *
*–  Dwayne Johnson  **–*


Vào Th 4, 19 thg 4, 2023 vào lúc 23:17 Luiz Estácio | stacio.eth <
***@***.***> đã viết:
