### ISSUE TITLE
Can't add liquidity and mint / sell nft

### ISSUE THREAD

**Issue by Loojk76H** [FuelLabs/fuels-wallet#711]
### What version of Wallet are you using?

The latest, i've downloaded it 2 days ago

### What is happening?

When i'm trying to add liquidity nothing happens, money is still on my wallet.
Also i can't sell / mint nft on fuelart with following error: Minting failed, please try again!

### steps to reproduce

1) Connect wallet on https://fuellabs.github.io/swayswap/pool/list , try to add liquidity
2) Create or sell nft on https://fuelart.io/create-item

### How it should behave?

When i charge money to pool, money should be in pool liqudity, not on my wallet.
There shouldn't be error on fuel art

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
Hi, @Loojk76H thanks for the report.

1. I have run on the same way you did here and was not able to see the issue you mentioned some info to note;
   - When adding liquidity or Swap, the assets used are sETH and DAI, not ETH the balance change will be on these two coins and not on ETH.
   - I found one bug maybe related to it: https://github.com/FuelLabs/swayswap/issues/411
 2. About FuelArt, this is an issue related to the Application / Rules itself. Please contact the FuelArt team through their community, they have a discord.
