### ISSUE TITLE
钱包插件不断断线重连

### ISSUE THREAD

**Issue by yuye7xing** [FuelLabs/fuels-wallet#718]
### What version of Wallet are you using?

0.7.2

### What is happening?

钱包安装上之后，哪怕不连接也在不断的断线重连

### steps to reproduce

安装插件
打开控制台，不断刷新
[FUEL WALLET] reconnecting!
[FUEL WALLET] reconnected!
[FUEL WALLET] reconnecting!
TFUEL WALLET] reconnected!

### How it should behave?

不使用的时候不要不断连接

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by tibi77** [comment]
How did you install the wallet?
Are you running the local node?
Could you share a screenshot of the console?

**Comment by Braqzen** [comment]
In English.
