### ISSUE TITLE
Creation of NFT does not work

### ISSUE THREAD

**Issue by scarlet1000** [FuelLabs/fuels-wallet#720]
### What version of Wallet are you using?

Beta-3

### What is happening?

From: https://fuelart.io/launchpad/0x5d4f41b5e6249cca9d0a7c0af4a84ad802de75076a42e8af538eef76f0900729
I tried to mint an NFT. The Fuel wallet opened and I confirmed payment of 0.10 ETH. I waited for more than 10 minutes and I did not see the NFT in my profile. 

I also tried "Create Item" and I got the message: All the NFTs are already minted!

### steps to reproduce

Go to: https://fuelart.io/launchpad/0x5d4f41b5e6249cca9d0a7c0af4a84ad802de75076a42e8af538eef76f0900729
and mint an NFT

### How it should behave?

I need to see the NFT in my profile

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Brave

**Comment by Netonedim** [comment]
![fuelart2](https://github.com/FuelLabs/fuels-wallet/assets/116693284/50e403c7-0eba-469d-91e4-0cdc6fd9e56a)
