### ISSUE TITLE
Sending Custom Asset issue

### ISSUE THREAD

**Issue by diyahir** [FuelLabs/fuels-wallet#730]
### What version of Wallet are you using?

0.7.2

### What is happening?

I can send ETH 0x000..000 reaching the 'approved transaction' page. But my custom asset does not reach the 'approve transaction' page it flashes and then reverts to the 'send' page.

### steps to reproduce

1. go to swaylend https://app.swaylend.com/#/faucet
2. get asset
3. try to send to another address 

### How it should behave?

Should be able to send asset 

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

**Comment by luizstacio** [comment]
@diyahir thanks for the report, we were already working on a fix  and was released on #737
