### ISSUE TITLE
 When connecting the wallet, it knocks out an error and hangs indefinitely

### ISSUE THREAD

**Issue by flatlinkin** [FuelLabs/fuels-wallet#750]
### What version of Wallet are you using?

0.0.1

### What is happening?

When connecting the wallet, it knocks out an error and hangs indefinitely

"Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key. DataError: Failed to execute 'boud' on..."

### steps to reproduce

When connecting the wallet knocks out an error

### How it should behave?

Should connect and work

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by Mrsumonsk** [comment]
F
