### ISSUE TITLE
Adding chrome extension to wallet install documentation

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/fuels-wallet#772]
### Motivation

Installing the Fuels wallet on chromium browsers via zip file will be deprecated for chrome extension. @sdankel has expressed issues with errors that makes users need to reinstall because of it's instability. 
![image](https://github.com/FuelLabs/fuels-wallet/assets/106365423/2f852b60-5edb-406b-bcdd-c6e7928929fc)

### Usage example

<img width="1512" alt="Screenshot 2023-05-30 at 3 36 20 PM" src="https://github.com/FuelLabs/fuels-wallet/assets/106365423/9b2c8dc5-f289-4d8e-ad46-5c00a800bcd6">

### Possible implementations

Simply update the readme section [here](https://wallet.fuel.network/docs/install/) as well as provide an updated video.  As well as add a 

Download Fuel Wallet
- "Chrome Store Button"
- "Zip File Button"

**Comment by luizstacio** [comment]
closed by: #791
