### ISSUE TITLE
DatabaseClosedError Database has been closed

### ISSUE THREAD

**Issue by static0man** [FuelLabs/fuels-wallet#778]
### What version of Wallet are you using?

0.8.0

### What is happening?

'unlock your wallet to continue' discover

### steps to reproduce

qqqqqq

### How it should behave?

qqqqqqqqqqqqq

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

114

**Comment by luizstacio** [comment]
Please update your wallet to version 0.10 via Chrome Web Store: https://wallet.fuel.network/docs/install/
