### ISSUE TITLE
Use hex name by default instead of bech32

### ISSUE THREAD

**Issue by diyahir** [FuelLabs/fuels-wallet#797]
### Motivation

Using "fuel1...." is bad UX for 99% of users who will be coming from Ethereum. Where the same mnemonic will result in an inconsistent experience. When bridging assets etc, it can lead to confusion if the assets are really going to the right place etc. 

These are the generated from the same private key:
<img width="214" alt="Screenshot 2023-06-30 at 11 20 30" src="https://github.com/FuelLabs/fuels-wallet/assets/32445955/f03c268b-ca94-49c4-9ca0-0098ff94978e">

<img width="372" alt="Screenshot 2023-06-30 at 11 23 03" src="https://github.com/FuelLabs/fuels-wallet/assets/32445955/f99edc77-8a7e-4446-b434-1c6c256ec0b7">

I recommend following in the path of other rollups in keeping the address the same since users are already familiar with that.

This is one of the biggest UX hurdles that the cosmos ecosystem faces where each chain decides its prefix and causes inconsistent naming, "cosmos1a...", "osmo1b...", "akash1c..." for the same wallet. Ask anyone in that ecosystem, if they could redo it from the beginning and use "0x..." they definitely would.

EVM chains avoid this by keeping the same "0x....." address. There is a 1:1 between the hex address and the bech32 address so let's make sure we aren't introducing unnecessary friction for user adoption and experience. 

I would love to hear the team's thoughts on this. I completely understand the desire to be unique in this sense, but it comes at the cost of UX and friction, which is a hard less that the cosmos ecosystem has learned.

**Comment by luizstacio** [comment]
Hi @diyahir thanks for the issue to improve the Fuel Network and our current Wallet.

Some things to consider;
- On Fuel address are longer by default, not matching the HEX address from ETH, even if we just show the HEX it would be different from ETH.
- The bech32 addresses improve the UX enabling validating network, typos directly on the address.

For now we don't have plans to move out from bech32 addresses but on the Wallet we plan to add support for visualizing the HEX address. #800

**Comment by diyahir** [comment]
I would disagree with the 2nd point on improving UX, additionally, there's a one-to-one mapping between hex and bech32, so it's unclear how they don't match, can you link me to more information on this?

I think this is a big mistake, even if it seems irrelevant
