### ISSUE TITLE
ошибка при создании кошелька

### ISSUE THREAD

**Issue by Seldman** [FuelLabs/fuels-wallet#855]
### What version of Wallet are you using?

1

### What is happening?

Запускаю регистрацию кошелька, записываю 12 слов, ввожу пароль и выскакивает неожиданная ошибка , которая не проходит и не пускает дальше

### steps to reproduce

1

### How it should behave?

должен создаться кошелек, а по факту все слетает

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

116.0.5845.141

**Comment by Braqzen** [comment]
In English.

**Comment by Seldman** [comment]
I start the wallet registration, write down 12 words, enter the password and an unexpected error pops up, which does not go through and does not allow further
