### ISSUE TITLE
Disable copy and paste of password in Wallet creation

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-wallet#856]
When creating a wallet you are prompted with a password selection screen.
This screen has 2 inputs. 
- 1 to enter the password that you want and 
- underneath another to confirm the password

The confirmation input allows you to paste from the clipboard.
This means you may typo a password, copy and paste it into the confirmation input and then continue setting up the wallet leading to being unable to unlock the wallet in the future.

**Comment by anubhav1206** [comment]
Where exactly is the file located?
