### ISSUE TITLE
Updating the wallet to a newer version without reinstalling

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-wallet#885]
### Motivation

If this is not already implemented then it would be good to provide the user with a way to upgrade the wallet extension when a newer release is available.

The chrome store provides notifications, to my knowledge, when a newer version of an extension is available. The user may then choose to update or ignore the notification.

It's not a good idea to force automatic updates even if that is possible.

The notification in the browser is a better solution than adding a button to the wallet since the store infra should handle that already. That being said, a "hidden away" button in the settings would not be a bad idea.

This behaviour would fix the need for going to the store to reinstall the extension with the latest release and then recover the wallet.

**Comment by luizstacio** [comment]
The solution for this issue is been tracked here: https://github.com/FuelLabs/fuels-wallet/issues/928
