### ISSUE TITLE
Don't install and work fuel wallet

### ISSUE THREAD

**Issue by Alena0708** [FuelLabs/fuels-wallet#904]
### What version of Wallet are you using?

Last one, which available on internet site

### What is happening?

I want to install under google chrome for windows 7 Home Base and under this operation system. Can you give me the version of Fuel wallet for windows 7 Home Base, which successfuly installing and working. Thank you.   

### steps to reproduce

When I want to start to installing in google play, the system send me a windows with mistakes.

### How it should behave?

It should installing and working. 

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Версия 109.0.5414.120 (Официальная сборка), (32 бит)

**Comment by luizstacio** [comment]
duplicate: #912
