### ISSUE TITLE
mint problem

### ISSUE THREAD

**Issue by pandachaincd** [FuelLabs/fuels-wallet#905]
### What version of Wallet are you using?

0.13.0

### What is happening?

i can't mint asset

### steps to reproduce

mint asset

### How it should behave?

solve that problem

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

117.0.5938.134

**Comment by luizstacio** [comment]
@pandachaincd  where have you try to mint the asset?
