### ISSUE TITLE
Not able to add Beta-3 network

### ISSUE THREAD

**Issue by ymart1n** [FuelLabs/fuels-wallet#907]
### What version of Wallet are you using?

0.13.0

### What is happening?

When I tried to add the Beta-3 network to the wallet, it failed.

![image](https://github.com/FuelLabs/fuels-wallet/assets/56213581/af4c37c1-acf8-4630-9b01-9211e0d0062b)

### steps to reproduce

Go to wallet extension --> Add New Network --> Enter "https://beta-3.fuel.network/graphql"

### How it should behave?

I'm not very sure if there is any documentation about the migration but it should probably let me add the Beta-3 testnet.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
The beta-3 is not compatible with version 0.13 of the wallet. Only beta-4 to use beta-3 you can install using the zip file: https://github.com/FuelLabs/fuels-wallet/releases/tag/v0.12.1 but we recommend you migrate as beta-3 is set to be discontinued.
