### ISSUE TITLE
Create a start page for wallet application for preview envs

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#91]
We should be able to test the wallet the way users will directly on the preview links from the repository, enabling anyone to play with the wallet.

This task should implement this start page with some actions;
- Open Wallet
- See storybook

**Comment by pedronauck** [comment]
Should we do some kinda a design for this or we're talking just about buttons? @luizstacio

**Comment by luizstacio** [comment]
> Should we do some kinda a design for this or we're talking just about buttons? @luizstacio

Just two buttons centered are good for now.
