### ISSUE TITLE
Import wallet seed phrase is showing a vertical and horizontal scroll

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#93]
The page should have all content inside the screen and no scroll. Resolution: `1280x768`.

<img width="500" alt="Screen Shot 2022-09-07 at 11 07 07 PM" src="https://user-images.githubusercontent.com/3941923/189017699-2f141b40-d3c0-4b00-afbb-63161a83ad83.png">

**Comment by pedronauck** [comment]
@luizstacio can you provide more information about this? I tried here on Brave using `1280x768` resolution with response view and didn't find this bug.

**Comment by luizstacio** [comment]
> @luizstacio can you provide more information about this? I tried here on Brave using `1280x768` resolution with response view and didn't find this bug.

This is very consistent here, but only on the recover wallet, and the warning opened `This wallet is current on development, and your phrase is not safely stored, DO NOT IMPORT YOUR CURRENT SEED PHRASE.`.

<img width="1413" alt="Screen Shot 2022-09-12 at 2 43 42 PM" src="https://user-images.githubusercontent.com/3941923/189721357-48fd9348-d824-458a-9fb0-b0fa94166cad.png">
