### ISSUE TITLE
Showing wrong card when adding asset without "name" prop

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#935]
![image](https://github.com/FuelLabs/fuels-wallet/assets/3941923/f0349c67-ce9f-4410-a520-7eece48dd46e)

**Comment by Another-DevX** [comment]
how i can work on this?
I mean, basically what should I say in this edge case?

**Comment by luizstacio** [comment]
@Another-DevX we should reject Add assets without a name. The Assets Service that handle this, should validate and if the name is not informed, it should throw a error.
