### ISSUE TITLE
swaylend Add SwaySwap assets don't work

### ISSUE THREAD

**Issue by skyyu2810** [FuelLabs/fuels-wallet#962]
### What version of Wallet are you using?

4

### What is happening?

https://fuellabs.github.io/swayswap/    Add SwaySwap assets don't work

### steps to reproduce

Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid

### How it should behave?

connect wallet

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by luizstacio** [comment]
Thanks for opening an issue, 

SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.

About SwayLend they have update the application and it's currently working.
