### ISSUE TITLE
cant conect it doesnt seems to register my wallet

### ISSUE THREAD

**Issue by duka511** [FuelLabs/fuels-wallet#970]
### What version of Wallet are you using?

beta4

### What is happening?

cant conect always going to install

### steps to reproduce

it doesnt recognize it and giving me instsall all the time

### How it should behave?

it should conect

### What os are you seeing the problem on?

Windows Desktop

### What browser?

None

### What is your browser version?

chrome

**Comment by luizstacio** [comment]
Thanks for the issue, closings this one in favor of https://github.com/FuelLabs/fuels-wallet/issues/1019
