### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'movi') Minting any other token other then Test ETH from https://app.swaylend.com/#/faucet

### ISSUE THREAD

**Issue by PedroMorningStar** [FuelLabs/fuels-wallet#981]
### What version of Wallet are you using?

0.13.5

### What is happening?

1)  TypeError: Cannot read properties of undefined (reading 'movi') 
(Minting any other token other then Test ETH from https://app.swaylend.com/#/faucet)

2) Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid
https://fuellabs.github.io/swayswap/welcome/add-assets 
( I connect wallet could not add asset)

### steps to reproduce

1) Typed in url https://fuellabs.github.io/swayswap/welcome/add-assets 
(Minting any other token other then Test ETH from https://app.swaylend.com/#/faucet)
Error Output:  Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid

2) Typed in url https://app.swaylend.com/#/faucet
(Minting any other token other then Test ETH from https://app.swaylend.com/#/faucet)
Error Output:  TypeError: Cannot read properties of undefined (reading 'movi') 

### How it should behave?

Should work

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

1.3.36.332

**Comment by luizstacio** [comment]
Thanks for opening an issue,

SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.

About SwayLend they have update the application and it's currently working. If you have issues on swaylend yet you can report directly on their repository https://github.com/compolabs/sway-lend.
