### ISSUE TITLE
swaylend Add SwaySwap assets fails

### ISSUE THREAD

**Issue by Ejiniemmanuel** [FuelLabs/fuels-wallet#985]
### What version of Wallet are you using?

Version: 0.13.5

### What is happening?

The add asset function is not working. If you click on add asset, it pops up a bug error. 
**Asset 0x1bdeed96ee1e5eca0bd1d7eeeb51d03b0202c1faf764fec1b276ba27d5d61d89 decimals is not valid**

### steps to reproduce

add

### How it should behave?

It should add automatically upon clicking

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by kachi90** [comment]
i'm having similar issues

**Comment by Bimzzy** [comment]
same here

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.
