### ISSUE TITLE
Transaction History menu shows error

### ISSUE THREAD

**Issue by severian44** [FuelLabs/fuels-wallet#986]
### What version of Wallet are you using?

0.13.5

### What is happening?

When I click on "Transaction History" in the wallet's menu, it doesn't show up, instead the error occurs. It has the following log:

{
  "error": {},
  "reactError": {
    "componentStack": "\n    at G2 (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:395:47995)\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:334:18615\n    at Od (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:395:49980)\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:334:18615\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:334:18615\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:398:18986\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:334:18615\n    at div\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:334:18615\n    at main\n    at chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:334:18615\n    at Be (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:398:19175)\n    at xae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:395:50230)\n    at hne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:3759)\n    at hne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:3759)\n    at af (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:6323)\n    at O9 (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:396:7900)\n    at hne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:3759)\n    at af (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:6323)\n    at U9 (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:398:24548)\n    at z9 (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:398:24690)\n    at $ce\n    at hne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:3759)\n    at P2 (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:6949)\n    at _ne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:373:5934)\n    at t (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:373:8028)\n    at Hae (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:396:1640)\n    at vee (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:342:2393)\n    at mle (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:398:25290)\n    at Vce\n    at xne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:364:6383)\n    at Sne (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:373:419)\n    at yle (chrome-extension://dldjpboieedgcmpkchcjcbijingjcgok/assets/main-1b1b8631.js:398:26725)"
  },
  "timestamp": 1700609893602,
  "id": "62a33658-1ede-472b-af08-1d61bd4f8da2"
}

Screen:
<img width="364" alt="screen 2023-11-21 232022" src="https://github.com/FuelLabs/fuels-wallet/assets/96204521/71be9aca-2db2-4393-a92a-678a58e5fed2">

### steps to reproduce

I installed the wallet today and made some transactions (my address is: fuel1jh8plckf9wg24z8plpl7pentn3gqtadqp83jysvegm54tlepwv3qsjj457). Then I went to the menu and clicked on "Transaction History". The error occured. I can close error and return to the wallet, but Transaction History doesn't work (everything else does). I tried to restart system but this error commences each time I try to go to Transaction History.

### How it should behave?

Transaction History shall show properly.

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by luizstacio** [comment]
@severian44 this error is still happening on the latest version of the Fuel Wallet (0.13.10)? We made some fixes on the Transaction History, related to some unsupported types.

**Comment by luizstacio** [comment]
@severian44 I have tested the transaction history on the latest version 0.13.10 of the Fuel Wallet, and the error it not happening here. Please if the error still there let me know.
