### ISSUE TITLE
ASSEST MINT

### ISSUE THREAD

**Issue by Bhussyjoe** [FuelLabs/fuels-wallet#989]
### Motivation

The swayswap assests mint as been lagging for quite a while now

**Comment by luizstacio** [comment]
Thanks for opening an issue, SwaySwap is no longer maintained, this is why you experienced the issues. We have updated the project readme to better inform other users.

**Comment by Bhussyjoe** [comment]
So what do we do, which swapping platform do we make use of, and can you direct me to the read me

**Comment by luizstacio** [comment]
@Bhussyjoe we can see the list of projects to test the network here: https://app.fuel.network/portal/ecosystem
And this is the link to the [readme](https://github.com/FuelLabs/swayswap?tab=readme-ov-file#%EF%B8%8F-support-notice-%EF%B8%8F)
