### ISSUE TITLE
Text for creating a new account in an existing wallet

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-wallet#992]
This is a minor issue with the messages when creating an account.

We use the word "Add" for both importing and creating a new account.

We should change the text to be "Import from private key" and "Create new account" as that is accurately describing what is happening.

![1](https://github.com/FuelLabs/fuels-wallet/assets/103777923/aa64da45-7c17-4d3b-a53f-b442c1279fac)

**Comment by sfazli96** [comment]
Hi, if possible can I get assigned to this? I can look into and see if I can fix the issue.

**Comment by sfazli96** [comment]
nevermind, I see that this issue will close soon
